RPC_MAX_RESEND_ITER = 20
RPC_RETRY_SLEEP_TIME_IN_SECS = 180
DEFAULT_RECEIPT_MAX_RETRY: int = 10
DEFAULT_BLOCK_PERIOD_SECS: int = 3
DEFAULT_BLOCK_AGING_BLOCKS: int = 1
DEFAULT_RPC_RESEND_DELAY_SEC: int = 180
DEFAULT_RPC_TX_BLOCK_DELAY: int = 2


DEFAULT_CHAIN_NAME = "DEFAULT_CHAIN"
