RPC_MAX_RESEND_ITER: int = 20
RPC_RETRY_SLEEP_TIME_IN_SECS: int = 180
DEFAULT_RECEIPT_MAX_RETRY: int = 20
DEFAULT_BLOCK_PERIOD_SECS: int = 13
DEFAULT_BLOCK_AGING_BLOCKS: int = 6
DEFAULT_RPC_RESEND_DELAY_SEC: int = 180
DEFAULT_RPC_TX_BLOCK_DELAY: int = 3


DEFAULT_CHAIN_NAME: str = "NONE_CHAIN"
