BINANCE_SYMBOL_TO_ANCHORS = {
    "ETH": ["BTC", "USDT", "BUSD"],
    "LTC": ["BTC", "ETH", "USDT", "BNB", "BUSD"],
    "BNB": ["BTC", "ETH", "USDT", "BUSD"],
    "NEO": ["BTC", "ETH", "USDT", "BNB", "BUSD"],
    "QTUM": ["ETH", "BTC", "BNB", "USDT", "BUSD"],
    "EOS": ["ETH", "BTC", "USDT", "BNB", "BUSD"],
    "SNT": ["ETH", "BTC", "BUSD"],
    "BNT": ["ETH", "BTC", "USDT", "BUSD"],
    "BCC": ["BTC", "ETH", "USDT", "BNB"],
    "GAS": ["BTC", "BUSD"],
    "BTC": ["USDT", "BUSD"],
    "HSR": ["BTC", "ETH"],
    "OAX": ["ETH", "BTC"],
    "DNT": ["ETH", "BTC", "BUSD", "USDT"],
    "MCO": ["ETH", "BTC", "BNB", "USDT"],
    "ICN": ["ETH", "BTC"],
    "WTC": ["BTC", "ETH", "BNB", "USDT"],
    "LRC": ["BTC", "ETH", "BUSD", "USDT", "BNB"],
    "YOYO": ["BTC", "ETH", "BNB"],
    "OMG": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "ZRX": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "STRAT": ["BTC", "ETH", "BUSD", "BNB", "USDT"],
    "SNGLS": ["BTC", "ETH"],
    "BQX": ["BTC", "ETH"],
    "KNC": ["BTC", "ETH", "BUSD", "USDT", "BNB"],
    "FUN": ["BTC", "ETH", "USDT", "BNB"],
    "SNM": ["BTC", "ETH", "BUSD"],
    "IOTA": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "LINK": ["BTC", "ETH", "USDT", "BUSD", "BNB"],
    "XVG": ["BTC", "ETH", "BUSD", "USDT"],
    "SALT": ["BTC", "ETH"],
    "MDA": ["BTC", "ETH"],
    "MTL": ["BTC", "ETH", "USDT", "BUSD"],
    "SUB": ["BTC", "ETH"],
    "ETC": ["ETH", "BTC", "USDT", "BNB", "BUSD"],
    "MTH": ["BTC", "ETH"],
    "ENG": ["BTC", "ETH"],
    "ZEC": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "AST": ["BTC", "ETH"],
    "DASH": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "BTG": ["BTC", "ETH", "BUSD", "USDT"],
    "EVX": ["BTC", "ETH"],
    "REQ": ["BTC", "ETH", "USDT", "BUSD"],
    "VIB": ["BTC", "ETH", "BUSD"],
    "TRX": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "POWR": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "ARK": ["BTC", "ETH", "BUSD"],
    "XRP": ["BTC", "ETH", "USDT", "BNB", "BUSD"],
    "MOD": ["BTC", "ETH"],
    "ENJ": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "STORJ": ["BTC", "ETH", "BUSD", "USDT"],
    "VEN": ["BNB", "BTC", "ETH", "USDT"],
    "KMD": ["BTC", "ETH", "BUSD", "USDT"],
    "NULS": ["BNB", "BTC", "ETH", "USDT", "BUSD"],
    "RCN": ["BTC", "ETH", "BNB"],
    "RDN": ["BTC", "ETH", "BNB"],
    "XMR": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "DLT": ["BNB", "BTC", "ETH"],
    "AMB": ["BTC", "ETH", "BNB", "BUSD"],
    "BAT": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "BCPT": ["BTC", "ETH", "BNB", "PAX"],
    "ARN": ["BTC", "ETH"],
    "GVT": ["BTC", "ETH"],
    "CDT": ["BTC", "ETH"],
    "GXS": ["BTC", "ETH", "USDT", "BNB"],
    "POE": ["BTC", "ETH"],
    "QSP": ["BTC", "ETH", "BNB"],
    "BTS": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "XZC": ["BTC", "ETH", "BNB", "USDT"],
    "LSK": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "TNT": ["BTC", "ETH"],
    "FUEL": ["BTC", "ETH"],
    "MANA": ["BTC", "ETH", "BUSD", "USDT", "BNB"],
    "BCD": ["BTC", "ETH"],
    "DGD": ["BTC", "ETH"],
    "ADX": ["BTC", "ETH", "BNB", "BUSD", "USDT"],
    "ADA": ["BTC", "ETH", "USDT", "BNB", "BUSD"],
    "PPT": ["BTC", "ETH"],
    "CMT": ["BTC", "ETH", "BNB"],
    "XLM": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "CND": ["BTC", "ETH", "BNB"],
    "LEND": ["BTC", "ETH", "USDT", "BUSD"],
    "WABI": ["BTC", "ETH", "BNB"],
    "TNB": ["BTC", "ETH"],
    "WAVES": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "GTO": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "ICX": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "OST": ["BTC", "ETH", "BNB"],
    "ELF": ["BTC", "ETH", "USDT", "BUSD"],
    "AION": ["BTC", "ETH", "BNB", "BUSD", "USDT"],
    "NEBL": ["BTC", "BNB", "BUSD", "USDT"],
    "BRD": ["BTC", "ETH", "BNB"],
    "EDO": ["BTC", "ETH"],
    "WINGS": ["BTC", "ETH"],
    "NAV": ["BTC", "ETH", "BNB"],
    "LUN": ["BTC", "ETH"],
    "TRIG": ["BTC", "ETH", "BNB"],
    "APPC": ["BTC", "ETH", "BNB"],
    "VIBE": ["BTC", "ETH"],
    "RLC": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "INS": ["BTC", "ETH"],
    "PIVX": ["BTC", "BNB"],
    "IOST": ["BTC", "ETH", "USDT", "BUSD"],
    "CHAT": ["BTC", "ETH"],
    "STEEM": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "NANO": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "VIA": ["BTC", "ETH", "BNB"],
    "BLZ": ["BTC", "ETH", "BNB", "BUSD", "USDT"],
    "AE": ["BTC", "ETH", "BNB"],
    "RPX": ["BTC", "ETH", "BNB"],
    "NCASH": ["BTC", "ETH", "BNB"],
    "POA": ["BTC", "ETH", "BNB"],
    "ZIL": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "ONT": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "STORM": ["BTC", "ETH", "BNB", "USDT"],
    "XEM": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "WAN": ["BTC", "ETH", "BNB", "USDT"],
    "WPR": ["BTC", "ETH"],
    "QLC": ["BTC", "ETH", "BNB"],
    "SYS": ["BTC", "ETH", "BNB", "BUSD", "USDT"],
    "GRS": ["BTC", "ETH"],
    "CLOAK": ["BTC", "ETH"],
    "GNT": ["BTC", "ETH", "BNB"],
    "LOOM": ["BTC", "ETH", "BNB", "BUSD"],
    "BCN": ["BTC", "ETH", "BNB"],
    "REP": ["BTC", "BNB", "BUSD", "USDT"],
    "TUSD": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "ZEN": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "SKY": ["BTC", "ETH", "BNB"],
    "CVC": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "THETA": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "IOTX": ["BTC", "ETH", "USDT", "BUSD"],
    "QKC": ["BTC", "ETH", "BUSD"],
    "AGI": ["BTC", "ETH", "BNB"],
    "NXS": ["BTC", "ETH", "BNB"],
    "DATA": ["BTC", "ETH", "BUSD", "USDT"],
    "SC": ["BTC", "ETH", "USDT", "BUSD"],
    "NPXS": ["BTC", "ETH", "USDT"],
    "KEY": ["BTC", "ETH", "USDT", "BUSD"],
    "NAS": ["BTC", "ETH", "BNB"],
    "MFT": ["BTC", "ETH", "BNB", "USDT"],
    "DENT": ["BTC", "ETH", "USDT", "BUSD"],
    "ARDR": ["BTC", "ETH", "BNB", "USDT"],
    "HOT": ["BTC", "ETH", "BNB", "USDT", "BUSD"],
    "VET": ["BTC", "ETH", "USDT", "BNB", "BUSD"],
    "DOCK": ["BTC", "ETH", "USDT", "BUSD"],
    "POLY": ["BTC", "BNB", "BUSD", "USDT"],
    "PHX": ["BTC", "ETH", "BNB"],
    "HC": ["BTC", "ETH", "USDT"],
    "GO": ["BTC", "BNB"],
    "PAX": ["BTC", "BNB", "USDT", "ETH", "BUSD"],
    "RVN": ["BTC", "USDT", "BUSD"],
    "DCR": ["BTC", "BNB", "BUSD", "USDT"],
    "MITH": ["BTC", "BNB", "USDT"],
    "BCHABC": ["BTC", "USDT", "BUSD"],
    "BCHSV": ["BTC", "USDT", "PAX"],
    "REN": ["BTC", "BNB", "USDT", "BTC", "BUSD"],
    "BTT": ["BTC", "BNB", "USDT", "BUSD"],
    "USDS": ["USDT", "TUSD"],
    "ONG": ["BNB", "BTC", "USDT"],
    "FET": ["BNB", "BTC", "USDT", "BUSD"],
    "CELR": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "MATIC": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "ATOM": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "PHB": ["BNB", "BTC", "BUSD", "USDT"],
    "TFUEL": ["BNB", "BTC", "USDT", "BUSD"],
    "ONE": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "FTM": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "B": ["BTC", "ETH"],
    "ALGO": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "USDSB": ["USDT"],
    "ERD": ["BNB", "BTC", "USDT", "BUSD"],
    "DOGE": ["BNB", "BTC", "USDT", "BUSD"],
    "DUSK": ["BNB", "BTC", "USDT", "BUSD"],
    "ANKR": ["BNB", "BTC", "USDT", "BUSD"],
    "WIN": ["BNB", "BTC", "USDT", "BUSD"],
    "COS": ["BNB", "BTC", "USDT", "BUSD"],
    "COCOS": ["BNB", "BTC", "USDT", "BUSD"],
    "TOMO": ["BNB", "BTC", "USDT", "BUSD"],
    "PERL": ["BNB", "BTC", "USDT"],
    "CHZ": ["BNB", "BTC", "USDT", "BUSD"],
    "BAND": ["BNB", "BTC", "USDT", "BUSD"],
    "BUSD": ["USDT"],
    "BEAM": ["BNB", "BTC", "USDT"],
    "XTZ": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "HBAR": ["BNB", "BTC", "USDT", "BUSD"],
    "NKN": ["BNB", "BTC", "USDT", "BUSD"],
    "STX": ["BNB", "BTC", "USDT", "BUSD"],
    "KAVA": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "ARPA": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "CTXC": ["BNB", "BTC", "USDT", "BUSD"],
    "BCH": ["BNB", "BTC", "USDT", "BUSD"],
    "TROY": ["BNB", "BTC", "USDT", "BUSD"],
    "VITE": ["BNB", "BTC", "USDT", "BUSD"],
    "FTT": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "EUR": ["BUSD", "USDT"],
    "OGN": ["BNB", "BTC", "USDT", "BUSD"],
    "DREP": ["BNB", "BTC", "USDT", "BUSD"],
    "BULL": ["USDT", "BUSD"],
    "BEAR": ["USDT", "BUSD"],
    "ETHBULL": ["USDT", "BUSD"],
    "ETHBEAR": ["USDT", "BUSD"],
    "TCT": ["BNB", "BTC", "USDT"],
    "WRX": ["BNB", "BTC", "USDT", "BUSD"],
    "LTO": ["BNB", "BTC", "USDT", "BUSD"],
    "EOSBULL": ["USDT", "BUSD"],
    "EOSBEAR": ["USDT", "BUSD"],
    "XRPBULL": ["USDT", "BUSD"],
    "XRPBEAR": ["USDT", "BUSD"],
    "MBL": ["BNB", "BTC", "USDT", "BUSD"],
    "COTI": ["BNB", "BTC", "USDT", "BUSD"],
    "BNBBULL": ["USDT", "BUSD"],
    "BNBBEAR": ["USDT", "BUSD"],
    "STPT": ["BNB", "BTC", "USDT", "BUSD"],
    "SOL": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "CTSI": ["BTC", "USDT", "BNB", "BUSD"],
    "HIVE": ["BNB", "BTC", "USDT", "BUSD"],
    "CHR": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "BTCUP": ["USDT"],
    "BTCDOWN": ["USDT"],
    "MDT": ["BNB", "BTC", "USDT", "BUSD"],
    "STMX": ["BTC", "ETH", "USDT", "BUSD"],
    "IQ": ["BNB", "BUSD"],
    "PNT": ["BTC", "USDT"],
    "GBP": ["BUSD", "USDT"],
    "DGB": ["BTC", "BUSD", "USDT"],
    "COMP": ["BTC", "BNB", "BUSD", "USDT"],
    "BKRW": ["USDT", "BUSD"],
    "SXP": ["BTC", "BNB", "BUSD", "USDT"],
    "SNX": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "ETHUP": ["USDT"],
    "ETHDOWN": ["USDT"],
    "ADAUP": ["USDT"],
    "ADADOWN": ["USDT"],
    "LINKUP": ["USDT"],
    "LINKDOWN": ["USDT"],
    "VTHO": ["BNB", "BUSD", "USDT"],
    "IRIS": ["BNB", "BTC", "BUSD", "USDT"],
    "MKR": ["BNB", "BTC", "USDT", "BUSD"],
    "DAI": ["BNB", "BTC", "USDT", "BUSD"],
    "RUNE": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "AUD": ["BUSD", "USDT"],
    "FIO": ["BNB", "BTC", "BUSD", "USDT"],
    "BNBUP": ["USDT"],
    "BNBDOWN": ["USDT"],
    "XTZUP": ["USDT"],
    "XTZDOWN": ["USDT"],
    "AVA": ["BNB", "BTC", "BUSD", "USDT"],
    "BAL": ["BNB", "BTC", "BUSD", "USDT"],
    "YFI": ["BNB", "BTC", "BUSD", "USDT"],
    "JST": ["BNB", "BTC", "BUSD", "USDT"],
    "SRM": ["BNB", "BTC", "BUSD", "USDT"],
    "ANT": ["BNB", "BTC", "BUSD", "USDT"],
    "CRV": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "SAND": ["BNB", "BTC", "USDT", "BUSD", "ETH"],
    "OCEAN": ["BNB", "BTC", "BUSD", "USDT"],
    "NMR": ["BTC", "BUSD", "USDT"],
    "DOT": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "LUNA": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "IDEX": ["BTC", "BUSD", "USDT", "BNB"],
    "RSR": ["BNB", "BTC", "BUSD", "USDT"],
    "PAXG": ["BNB", "BTC", "BUSD", "USDT"],
    "WNXM": ["BNB", "BTC", "BUSD", "USDT"],
    "TRB": ["BNB", "BTC", "BUSD", "USDT"],
    "BZRX": ["BNB", "BTC", "BUSD", "USDT"],
    "W": ["BTC"],
    "WBTC": ["ETH", "BUSD"],
    "SUSHI": ["BNB", "BTC", "BUSD", "USDT"],
    "YFII": ["BNB", "BTC", "BUSD", "USDT"],
    "KSM": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "EGLD": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "DIA": ["BNB", "BTC", "BUSD", "USDT"],
    "UMA": ["BTC", "USDT", "BUSD"],
    "EOSUP": ["USDT"],
    "EOSDOWN": ["USDT"],
    "TRXUP": ["USDT"],
    "TRXDOWN": ["USDT"],
    "XRPUP": ["USDT"],
    "XRPDOWN": ["USDT"],
    "DOTUP": ["USDT"],
    "DOTDOWN": ["USDT"],
    "BEL": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "WING": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "SWRV": ["BNB", "BUSD"],
    "LTCUP": ["USDT"],
    "LTCDOWN": ["USDT"],
    "CREAM": ["BNB", "BUSD"],
    "UNI": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "NBS": ["BTC", "USDT"],
    "OXT": ["BTC", "USDT", "BUSD"],
    "SUN": ["BTC", "USDT", "BUSD"],
    "AVAX": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "HNT": ["BTC", "USDT", "BUSD"],
    "BAKE": ["BNB", "BUSD", "USDT", "BTC"],
    "BURGER": ["BNB", "BUSD", "USDT", "ETH"],
    "FLM": ["BNB", "BTC", "BUSD", "USDT"],
    "SCRT": ["BTC", "ETH", "BUSD", "USDT"],
    "CAKE": ["BNB", "BUSD", "BTC", "USDT"],
    "SPARTA": ["BNB"],
    "UNIUP": ["USDT"],
    "UNIDOWN": ["USDT"],
    "ORN": ["BTC", "USDT", "BUSD"],
    "UTK": ["BTC", "USDT", "BUSD"],
    "XVS": ["BNB", "BTC", "BUSD", "USDT"],
    "ALPHA": ["BNB", "BTC", "BUSD", "USDT"],
    "VIDT": ["BTC", "BUSD", "USDT"],
    "AAVE": ["BNB", "BTC", "ETH", "BUSD", "USDT"],
    "NEAR": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "SXPUP": ["USDT"],
    "SXPDOWN": ["USDT"],
    "FIL": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "FILUP": ["USDT"],
    "FILDOWN": ["USDT"],
    "YFIUP": ["USDT"],
    "YFIDOWN": ["USDT"],
    "INJ": ["BNB", "BTC", "BUSD", "USDT"],
    "AERGO": ["BTC", "BUSD"],
    "EASY": ["ETH", "BTC"],
    "AUDIO": ["BTC", "BUSD", "USDT"],
    "CTK": ["BNB", "BTC", "BUSD", "USDT"],
    "BCHUP": ["USDT"],
    "BCHDOWN": ["USDT"],
    "BOT": ["BTC", "BUSD"],
    "AKRO": ["BTC", "USDT", "BUSD"],
    "KP3R": ["BNB", "BUSD", "USDT"],
    "AXS": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "HARD": ["BNB", "BTC", "BUSD", "USDT"],
    "RENBTC": ["ETH"],
    "SLP": ["ETH", "BUSD", "USDT", "BNB"],
    "CVP": ["ETH", "BUSD", "USDT"],
    "STRAX": ["BTC", "ETH", "BUSD", "USDT"],
    "FOR": ["BTC", "BUSD", "USDT", "BNB"],
    "UNFI": ["BNB", "BTC", "BUSD", "USDT", "ETH"],
    "FRONT": ["ETH", "BUSD", "BTC", "USDT"],
    "BCHA": ["BUSD"],
    "ROSE": ["BTC", "BUSD", "USDT", "BNB", "ETH"],
    "HEGIC": ["ETH", "BUSD"],
    "AAVEUP": ["USDT"],
    "AAVEDOWN": ["USDT"],
    "PROM": ["BNB", "BUSD", "BTC"],
    "SKL": ["BTC", "BUSD", "USDT"],
    "SUSD": ["BTC", "ETH", "USDT"],
    "COVER": ["ETH", "BUSD"],
    "GLM": ["BTC", "ETH", "BUSD"],
    "GHST": ["ETH", "BUSD", "USDT"],
    "SUSHIUP": ["USDT"],
    "SUSHIDOWN": ["USDT"],
    "XLMUP": ["USDT"],
    "XLMDOWN": ["USDT"],
    "DF": ["ETH", "BUSD", "USDT"],
    "GRT": ["BTC", "ETH", "USDT", "BUSD"],
    "JUV": ["BTC", "BUSD", "USDT"],
    "PSG": ["BTC", "BUSD", "USDT"],
    "1INCH": ["BTC", "USDT", "BUSD"],
    "REEF": ["BTC", "USDT", "BUSD"],
    "OG": ["BTC", "USDT", "BUSD"],
    "ATM": ["BTC", "USDT", "BUSD"],
    "ASR": ["BTC", "USDT", "BUSD"],
    "CELO": ["BTC", "USDT", "BUSD"],
    "RIF": ["BTC", "USDT"],
    "ST": ["BTC"],
    "BTCST": ["BUSD", "USDT"],
    "TRU": ["BTC", "BUSD", "USDT"],
    "DEXE": ["ETH", "BUSD", "USDT"],
    "CKB": ["BTC", "BUSD", "USDT"],
    "TWT": ["BTC", "BUSD", "USDT"],
    "FIRO": ["BTC", "ETH", "USDT", "BUSD"],
    "PROS": ["ETH", "BUSD"],
    "LIT": ["BTC", "BUSD", "USDT", "ETH"],
    "SFP": ["BTC", "BUSD", "USDT"],
    "FXS": ["BTC", "BUSD", "USDT"],
    "DODO": ["BTC", "BUSD", "USDT"],
    "UFT": ["ETH", "BUSD"],
    "ACM": ["BTC", "BUSD", "USDT"],
    "AUCTION": ["BTC", "BUSD", "USDT"],
    "PHA": ["BTC", "BUSD", "USDT"],
    "TVK": ["BTC", "BUSD", "USDT"],
    "BADGER": ["BTC", "BUSD", "USDT"],
    "FIS": ["BTC", "BUSD", "USDT"],
    "OM": ["BTC", "BUSD", "USDT"],
    "POND": ["BTC", "BUSD", "USDT"],
    "DEGO": ["BTC", "BUSD", "USDT"],
    "ALICE": ["BTC", "BUSD", "USDT", "BNB"],
    "LINA": ["BTC", "BUSD", "USDT", "BNB"],
    "PERP": ["BTC", "BUSD", "USDT"],
    "RAMP": ["BTC", "BUSD", "USDT"],
    "SUPER": ["BTC", "BUSD", "USDT"],
    "CFX": ["BTC", "BUSD", "USDT"],
    "EPS": ["BTC", "BUSD", "USDT"],
    "AUTO": ["BTC", "BUSD", "USDT"],
    "TKO": ["BTC", "BUSD", "USDT"],
    "PUNDIX": ["ETH", "USDT", "BUSD"],
    "TLM": ["BTC", "BUSD", "USDT", "BNB"],
    "1INCHUP": ["USDT"],
    "1INCHDOWN": ["USDT"],
    "MIR": ["BTC", "BUSD", "USDT"],
    "BAR": ["BTC", "BUSD", "USDT"],
    "FORTH": ["BTC", "BUSD", "USDT"],
    "EZ": ["BTC", "ETH"],
    "SHIB": ["USDT", "BUSD"],
    "ICP": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "AR": ["BTC", "BNB", "BUSD", "USDT"],
    "POLS": ["BTC", "BNB", "BUSD", "USDT"],
    "MDX": ["BTC", "BNB", "BUSD", "USDT"],
    "MASK": ["BNB", "BUSD", "USDT"],
    "LPT": ["BTC", "BNB", "BUSD", "USDT"],
    "AGIX": ["BTC", "BUSD"],
    "NU": ["BTC", "BNB", "BUSD", "USDT"],
    "ATA": ["BTC", "BNB", "BUSD", "USDT"],
    "GTC": ["BTC", "BNB", "BUSD", "USDT"],
    "TORN": ["BTC", "BNB", "BUSD", "USDT"],
    "KEEP": ["BTC", "BNB", "BUSD", "USDT"],
    "ERN": ["BNB", "BUSD", "USDT"],
    "KLAY": ["BTC", "BNB", "BUSD", "USDT"],
    "BOND": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "MLN": ["BTC", "BNB", "BUSD", "USDT"],
    "QUICK": ["BTC", "BNB", "BUSD", "USDT"],
    "C98": ["USDT", "BUSD", "BNB", "BTC"],
    "CLV": ["BTC", "BNB", "BUSD", "USDT"],
    "QNT": ["BTC", "BNB", "BUSD", "USDT"],
    "FLOW": ["BTC", "BNB", "BUSD", "USDT"],
    "XEC": ["BUSD", "USDT"],
    "MINA": ["BTC", "BNB", "BUSD", "USDT"],
    "RAY": ["BNB", "BUSD", "USDT"],
    "FARM": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "ALPACA": ["BTC", "BNB", "BUSD", "USDT"],
    "MBOX": ["BTC", "BNB", "BUSD", "USDT"],
    "VGX": ["BTC", "ETH", "USDT"],
    "WAXP": ["USDT", "BUSD", "BNB", "BTC"],
    "TRIBE": ["BTC", "BNB", "BUSD", "USDT"],
    "GNO": ["USDT", "BUSD", "BNB", "BTC"],
    "DYDX": ["USDT", "BUSD", "BNB", "BTC", "ETH"],
    "USDP": ["BUSD", "USDT"],
    "GALA": ["USDT", "BUSD", "BNB", "BTC", "ETH"],
    "ILV": ["USDT", "BUSD", "BNB", "BTC"],
    "YGG": ["USDT", "BUSD", "BNB", "BTC"],
    "FIDA": ["USDT", "BUSD", "BNB", "BTC"],
    "AGLD": ["BTC", "BNB", "BUSD", "USDT"],
    "RAD": ["BTC", "BNB", "BUSD", "USDT"],
    "BETA": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "RARE": ["BTC", "BNB", "BUSD", "USDT"],
    "SSV": ["BTC", "ETH", "BUSD"],
    "LAZIO": ["BTC", "USDT", "BUSD"],
    "CHESS": ["BTC", "BNB", "BUSD", "USDT"],
    "DAR": ["USDT", "BUSD", "BNB", "BTC", "ETH"],
    "BNX": ["BTC", "BNB", "BUSD", "USDT"],
    "RGT": ["USDT", "BTC", "BUSD", "BNB"],
    "MOVR": ["BTC", "BNB", "BUSD", "USDT"],
    "CITY": ["BTC", "BNB", "BUSD", "USDT"],
    "ENS": ["BTC", "BNB", "BUSD", "USDT"],
    "QI": ["USDT", "BUSD", "BNB", "BTC"],
    "PORTO": ["BTC", "USDT", "BUSD"],
    "JASMY": ["USDT", "BUSD", "BNB", "BTC", "ETH"],
    "AMP": ["BTC", "BNB", "BUSD", "USDT"],
    "PLA": ["BTC", "BNB", "BUSD", "USDT"],
    "PYR": ["BTC", "BUSD", "USDT"],
    "RNDR": ["BTC", "USDT", "BUSD"],
    "ALCX": ["BTC", "BUSD", "USDT"],
    "SANTOS": ["BTC", "USDT", "BUSD"],
    "MC": ["BTC", "BUSD", "USDT", "BNB"],
    "ANY": ["BTC", "BUSD", "USDT"],
    "BICO": ["BTC", "BUSD", "USDT"],
    "FLUX": ["BTC", "BUSD", "USDT"],
    "VOXEL": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "HIGH": ["BTC", "BUSD", "USDT", "BNB"],
    "CVX": ["BTC", "BUSD", "USDT"],
    "PEOPLE": ["BTC", "BUSD", "USDT", "BNB", "ETH"],
    "OOKI": ["BUSD", "USDT", "BNB", "ETH"],
    "SPELL": ["BTC", "USDT", "BUSD", "BNB"],
    "UST": ["BTC", "BUSD", "USDT"],
    "JOE": ["BTC", "BUSD", "USDT"],
    "ACH": ["BTC", "BUSD", "USDT"],
    "IMX": ["BTC", "BUSD", "USDT", "BNB"],
    "GLMR": ["BTC", "BUSD", "USDT", "BNB"],
    "LOKA": ["BTC", "BNB", "BUSD", "USDT"],
    "API3": ["BTC", "BUSD", "USDT", "BNB"],
    "BTTC": ["USDT", "BUSD"],
    "ACA": ["BTC", "BUSD", "USDT"],
    "ANC": ["BTC", "BUSD", "USDT", "BNB"],
    "XNO": ["BTC", "ETH", "BUSD", "USDT"],
    "WOO": ["BTC", "BNB", "BUSD", "USDT"],
    "ALPINE": ["USDT", "BTC", "BUSD"],
    "T": ["USDT", "BUSD"],
    "ASTR": ["BUSD", "USDT", "BTC", "ETH"],
    "NBT": ["USDT"],
    "GMT": ["BTC", "BNB", "BUSD", "USDT", "ETH"],
    "KDA": ["BTC", "BUSD", "USDT"],
    "APE": ["USDT", "BUSD", "BTC", "BNB", "ETH"],
    "BSW": ["USDT", "BUSD", "BNB", "ETH"],
    "MULTI": ["BTC", "BUSD", "USDT"],
    "MOB": ["USDT", "BUSD", "BTC"],
    "NEXO": ["USDT", "BUSD", "BTC"],
    "REI": ["USDT", "BNB", "ETH", "BUSD"],
    "GAL": ["USDT", "BUSD", "BNB", "BTC", "ETH"],
    "LDO": ["BUSD", "USDT", "BTC"],
    "EPX": ["USDT", "BUSD"],
    "LUNC": ["BUSD", "USDT"],
    "USTC": ["BUSD"],
    "OP": ["BTC", "BUSD", "USDT", "BNB", "ETH"],
    "LEVER": ["USDT", "BUSD"],
    "STG": ["BTC", "BUSD", "USDT"],
    "BETH": ["BUSD"],
    "GMX": ["BTC", "BUSD", "USDT"],
    "POLYX": ["BTC", "BUSD", "USDT"],
    "APT": ["BTC", "USDT", "BUSD"],
    "OSMO": ["BTC", "USDT", "BUSD"],
    "HFT": ["BTC", "BUSD", "USDT"],
    "HOOK": ["BTC", "USDT", "BUSD", "BNB"],
    "MAGIC": ["BTC", "BUSD", "USDT"],
    "HIFI": ["ETH", "USDT"],
    "RPL": ["BTC", "BUSD", "USDT"]
}

BINANCE_SUPPORTING_SYMBOLS = list(BINANCE_SYMBOL_TO_ANCHORS.keys())
