


GATE_IO_SYMBOL_TO_ANCHORS = {
    "USDT": [],
    "SRK": ['ETH', 'USDT'],
    "LBL": ['USDT'],
    "ISP": ['ETH', 'USDT'],
    "GRIN3S": ['USDT'],
    "DOWS": ['ETH', 'USDT'],
    "SLC": ['USDT', 'ETH'],
    "FRAX": ['ETH', 'USDT'],
    "CATGIRL": ['USDT'],
    "ROSN": ['USDT'],
    "MINE": ['USDT'],
    "NVIR": ['USDT'],
    "DOGE3L": ['USDT'],
    "REI": ['BTC', 'USDT'],
    "ELON": ['USDT'],
    "API33S": ['USDT'],
    "PRARE": ['ETH', 'USDT'],
    "GHST": ['USDT', 'ETH'],
    "EOSDAC": ['ETH', 'USDT'],
    "ERG": ['ETH', 'USDT'],
    "METAX": ['ETH', 'USDT'],
    "CDT": ['USDT', 'BTC', 'ETH'],
    "GAFI": ['ETH', 'USDT'],
    "CTK": ['USDT', 'ETH'],
    "VMT": ['USDT'],
    "RACA3S": ['USDT'],
    "EVA": ['ETH', 'USDT'],
    "ZEE": ['ETH', 'USDT'],
    "ICP": ['ETH', 'USDT'],
    "HT": ['BTC', 'USDT'],
    "OKT": ['ETH', 'USDT'],
    "OPEN": ['USDT', 'ETH'],
    "MPLX": ['USDT'],
    "SUPER": ['ETH', 'USDT'],
    "MCRN": ['USDT', 'ETH'],
    "TPT": ['ETH', 'USDT'],
    "THEOS": ['USDT'],
    "SYS": ['USDT', 'ETH'],
    "SPA": ['USDT', 'ETH'],
    "GOZ": ['USDT'],
    "AAVE3S": ['USDT'],
    "FNCY": ['USDT'],
    "RATIO": ['USDT'],
    "SIN": ['USDT'],
    "NII": ['USDT', 'ETH'],
    "ZLK": ['ETH', 'USDT'],
    "VGX": ['USDT', 'ETH'],
    "RSR": ['USDT'],
    "HERO": ['ETH', 'USDT'],
    "UNISTAKE": ['USDT', 'ETH'],
    "STRONG": ['USDT', 'ETH'],
    "DPY": ['USDT', 'ETH'],
    "RBC": ['USDT', 'ETH'],
    "KFC": ['USDT'],
    "PVU": ['ETH', 'USDT'],
    "CQT": ['ETH', 'USDT'],
    "TFUEL": ['ETH', 'USDT'],
    "METIS": ['USDT', 'ETH'],
    "BOND": ['ETH', 'USDT'],
    "WOO": ['ETH', 'USDT'],
    "BIRD": ['USDT', 'ETH'],
    "HARD": ['ETH', 'USDT'],
    "LIBRE": ['ETH', 'USDT'],
    "MEAN": ['USDT', 'ETH'],
    "XYM": ['ETH', 'USDT'],
    "NULS": ['ETH', 'USDT'],
    "MQL": ['USDT'],
    "STETH": ['USDT', 'ETH'],
    "ALPHR": ['ETH', 'USDT'],
    "LIQUIDUS": ['ETH', 'USDT'],
    "ALPA": ['USDT', 'ETH'],
    "ALEPH": ['ETH', 'USDT'],
    "KILT": ['USDT'],
    "FSN": ['ETH', 'USDT'],
    "SWINGBY": ['USDT', 'ETH'],
    "WAVES3L": ['USDT'],
    "ITA": ['USDT'],
    "DUSK": ['USDT', 'ETH'],
    "WAVES": ['USDT', 'BTC'],
    "LBA": ['ETH', 'USDT'],
    "LIT3S": ['USDT'],
    "LYXE": ['USDT', 'ETH'],
    "WSI": ['USDT'],
    "DDD": ['ETH', 'USDT', 'BTC'],
    "ZEC3S": ['USDT'],
    "LEMN": ['USDT'],
    "DDOS": ['USDT'],
    "FTT3S": ['USDT'],
    "BONDED": ['USDT', 'ETH'],
    "GRT": ['USDT', 'ETH'],
    "FUSE": ['ETH', 'USDT'],
    "DCR": ['BTC', 'USDT'],
    "METAG": ['USDT'],
    "MIX": ['ETH', 'USDT'],
    "WOOP": ['ETH', 'USDT'],
    "ABT": ['ETH', 'USDT'],
    "BTF": ['BTC', 'USDT'],
    "METAN": ['USDT'],
    "NUX": ['ETH', 'USDT'],
    "ADX": ['ETH', 'USDT'],
    "OCN": ['BTC', 'USDT', 'ETH'],
    "PNG": ['USDT'],
    "KOK": ['USDT'],
    "BLANKV2": ['USDT', 'ETH'],
    "BUY": ['USDT', 'ETH'],
    "SUPE": ['ETH', 'USDT'],
    "CELL": ['ETH', 'USDT'],
    "ZKS": ['ETH', 'USDT'],
    "STAKE": ['USDT'],
    "SNFT": ['USDT'],
    "PLA": ['ETH', 'USDT'],
    "LRC": ['USDT', 'ETH', 'BTC'],
    "1INCH": ['ETH', 'USDT'],
    "TBE": ['USDT'],
    "BAKE": ['ETH', 'USDT'],
    "GRND": ['USDT'],
    "EJS": ['USDT'],
    "BOO": ['USDT', 'ETH'],
    "ANT": ['USDT'],
    "EOS": ['ETH', 'USDT', 'BTC'],
    "ENV": ['USDT'],
    "BASE": ['ETH', 'USDT'],
    "XETA": ['USDT'],
    "LMR": ['BTC', 'USDT'],
    "GHC": ['USDT'],
    "GMEE": ['ETH', 'USDT'],
    "OCT": ['USDT'],
    "WING": ['ETH', 'USDT'],
    "SAND3S": ['USDT'],
    "VP": ['USDT'],
    "SLP3S": ['USDT'],
    "CVC": ['ETH', 'USDT'],
    "OPS": ['USDT', 'ETH'],
    "BRT": ['USDT'],
    "SKL": ['USDT'],
    "XCN": ['ETH', 'USDT'],
    "SWFTC": ['USDT'],
    "ELT": ['USDT'],
    "WICC": ['USDT', 'ETH'],
    "CRO3L": ['USDT'],
    "CORAL": ['USDT', 'ETH'],
    "LOOKS3L": ['USDT'],
    "IOTX": ['USDT', 'ETH'],
    "CPHR": ['USDT'],
    "TVK": ['ETH', 'USDT'],
    "DEGO": ['USDT'],
    "TAMA": ['USDT'],
    "PSY": ['USDT', 'ETH'],
    "LARIX": ['ETH', 'USDT'],
    "PEOPLE3L": ['USDT'],
    "GRAP": ['ETH', 'USDT'],
    "GAME": ['USDT'],
    "TAPT": ['USDT'],
    "STBU": ['ETH', 'USDT'],
    "CBK": ['ETH', 'BTC', 'USDT'],
    "RVN": ['USDT'],
    "MDS": ['USDT', 'ETH'],
    "GBPT": ['BTC', 'ETH', 'USDT'],
    "MLT": ['USDT'],
    "PROPS": ['USDT', 'ETH'],
    "SOUL": ['USDT', 'ETH'],
    "XPRT": ['USDT', 'ETH'],
    "STI": ['USDT'],
    "WBT": ['USDT'],
    "ETHBULL": ['USDT'],
    "UFT": ['USDT', 'ETH'],
    "PERC": ['USDT'],
    "IDV": ['ETH', 'USDT'],
    "DIO": ['USDT'],
    "NYZO": ['ETH', 'USDT'],
    "MANA": ['ETH', 'USDT'],
    "RAI": ['ETH', 'USDT'],
    "LAND": ['USDT'],
    "WHITE": ['ETH', 'USDT'],
    "KINT": ['ETH', 'USDT'],
    "QASH": ['USDT', 'BTC', 'ETH'],
    "SAO": ['USDT'],
    "MGA": ['USDT'],
    "FTM": ['USDT', 'ETH'],
    "AMPL3S": ['USDT'],
    "SNTR": ['ETH', 'USDT'],
    "TON": ['USDT'],
    "OCTO": ['ETH', 'USDT'],
    "OLT": ['USDT'],
    "QUACK": ['USDT'],
    "PERP": ['USDT', 'ETH'],
    "MELI": ['USDT'],
    "ETC3S": ['USDT'],
    "WAXL": ['USDT'],
    "OG": ['USDT'],
    "ZINU": ['USDT'],
    "ALPHA": ['ETH', 'USDT'],
    "BXC": ['ETH', 'USDT'],
    "BDX": ['USDT'],
    "XTZ3S": ['USDT'],
    "TSHP": ['USDT'],
    "SPO": ['USDT'],
    "WXT": ['USDT', 'ETH'],
    "LKR": ['USDT', 'ETH'],
    "YFII3L": ['USDT'],
    "1INCH3L": ['USDT'],
    "BU": ['ETH', 'USDT', 'BTC'],
    "TRU": ['ETH', 'USDT'],
    "STORE": ['USDT'],
    "CVX": ['ETH', 'USDT'],
    "SGB": ['USDT'],
    "EGLD": ['USDT', 'ETH'],
    "KCAL": ['USDT'],
    "WNXM": ['USDT', 'ETH'],
    "MOTG": ['USDT'],
    "BAL": ['USDT', 'ETH'],
    "RMRK": ['USDT'],
    "CATHEON": ['USDT'],
    "BTC3L": ['USDT'],
    "HSF": ['USDT'],
    "REP": ['ETH', 'USDT'],
    "LFW": ['USDT'],
    "XMON": ['ETH', 'USDT'],
    "DC": ['USDT'],
    "GRIN": ['BTC', 'USDT', 'ETH'],
    "LIFE": ['USDT', 'ETH'],
    "BAT3L": ['USDT'],
    "STRM": ['USDT'],
    "VTHO": ['USDT', 'ETH'],
    "STSOL": ['ETH', 'USDT'],
    "GASDAO": ['USDT'],
    "AART": ['USDT', 'ETH'],
    "BRWL": ['USDT'],
    "DG": ['ETH', 'USDT'],
    "MDF": ['USDT', 'ETH'],
    "DEK": ['USDT'],
    "BEAM": ['ETH', 'USDT', 'BTC'],
    "DFL": ['USDT'],
    "BTT": ['ETH', 'USDT'],
    "STEPG": ['ETH', 'USDT'],
    "CHZ3S": ['USDT'],
    "BTL": ['USDT'],
    "VSO": ['USDT', 'ETH'],
    "ONC": ['ETH', 'USDT'],
    "DBC": ['BTC', 'USDT', 'ETH'],
    "SKM": ['USDT', 'ETH'],
    "INK": ['BTC', 'USDT', 'ETH'],
    "MOFI": ['USDT'],
    "ILV": ['USDT', 'ETH'],
    "DAO": ['USDT', 'ETH'],
    "AXS3L": ['USDT'],
    "LON": ['ETH', 'USDT'],
    "NEER": ['USDT'],
    "REQ": ['ETH', 'USDT'],
    "ASTRO": ['ETH', 'USDT'],
    "RNDR": ['ETH', 'USDT'],
    "WEST": ['ETH', 'USDT'],
    "DATA": ['ETH', 'USDT'],
    "NMR": ['USDT', 'ETH'],
    "AKRO": ['ETH', 'USDT'],
    "BAT": ['ETH', 'BTC', 'USDT'],
    "SINGLE": ['USDT'],
    "ATOZ": ['USDT'],
    "API3": ['USDT', 'ETH'],
    "DVP": ['USDT', 'ETH'],
    "O3": ['ETH', 'USDT'],
    "FTT": ['ETH', 'USDT'],
    "SUTER": ['USDT'],
    "COVER": ['ETH', 'USDT'],
    "LOVELY": ['USDT'],
    "FEVR": ['USDT'],
    "BETU": ['ETH', 'USDT'],
    "ICE": ['ETH', 'USDT'],
    "QANX": ['USDT'],
    "UOS": ['USDT', 'ETH'],
    "GVR": ['USDT'],
    "APT3S": ['USDT'],
    "LSS": ['ETH', 'USDT'],
    "XCH": ['ETH', 'USDT'],
    "SMT": ['USDT', 'ETH'],
    "MOBI": ['USDT', 'ETH', 'BTC'],
    "COTI": ['USDT'],
    "CRYPTOFI": ['USDT'],
    "NEXT": ['USDT'],
    "TLOS": ['USDT', 'BTC'],
    "ETH5L": ['USDT'],
    "CARDS": ['USDT', 'ETH'],
    "ATD": ['USDT', 'ETH'],
    "DEVT": ['USDT'],
    "LAZIO": ['ETH', 'USDT'],
    "OAX": ['ETH', 'BTC', 'USDT'],
    "DV": ['USDT'],
    "PBR": ['ETH', 'USDT'],
    "SRP": ['USDT'],
    "AERGO": ['ETH', 'USDT'],
    "BCH": ['USDT', 'BTC'],
    "FIO": ['USDT', 'ETH'],
    "SERO3S": ['USDT'],
    "KONO": ['ETH', 'USDT'],
    "MKR": ['USDT', 'ETH'],
    "NBS": ['BTC', 'USDT'],
    "AAA": ['USDT', 'ETH'],
    "ISK": ['USDT'],
    "QTUM": ['BTC', 'ETH', 'USDT'],
    "LIME": ['BTC', 'ETH', 'USDT'],
    "MART": ['USDT'],
    "XNFT": ['USDT', 'ETH'],
    "LSK": ['USDT', 'BTC'],
    "GITCOIN": ['USDT', 'ETH'],
    "MATIC3S": ['USDT'],
    "EQX": ['USDT'],
    "BABYDOGE": ['USDT'],
    "BDP": ['USDT', 'ETH'],
    "NEST": ['USDT', 'ETH'],
    "SUKU": ['ETH', 'USDT', 'BTC'],
    "ZMT": ['USDT'],
    "ARTEM": ['USDT'],
    "ENJ": ['ETH', 'USDT'],
    "TOOLS": ['USDT', 'ETH'],
    "FOX": ['USDT', 'ETH'],
    "ASM": ['USDT', 'ETH'],
    "ETC": ['USDT', 'ETH', 'BTC'],
    "KLV": ['USDT', 'ETH'],
    "TFD": ['ETH'],
    "XPNET": ['USDT'],
    "WOM": ['ETH', 'USDT'],
    "SLIM": ['ETH', 'USDT'],
    "FIL": ['BTC', 'ETH', 'USDT'],
    "GO": ['ETH', 'USDT'],
    "CMP": ['USDT'],
    "P00LS": ['USDT'],
    "JULD": ['ETH', 'USDT'],
    "TRX": ['USDT', 'ETH'],
    "SKYRIM": ['USDT', 'ETH'],
    "GRT3L": ['USDT'],
    "ALTB": ['USDT'],
    "NFTX": ['ETH', 'USDT'],
    "POKT": ['USDT'],
    "ROOK": ['ETH', 'USDT'],
    "ORAO": ['ETH', 'USDT'],
    "FITFI": ['USDT'],
    "STORJ": ['USDT', 'ETH', 'BTC'],
    "BTC5S": ['USDT'],
    "MTV": ['USDT'],
    "YFDAI": ['USDT', 'ETH'],
    "KISHU": ['USDT'],
    "RAZOR": ['USDT', 'ETH'],
    "MAGIC": ['USDT'],
    "LOKA3L": ['USDT'],
    "DUCK2": ['ETH', 'USDT'],
    "TKO": ['USDT', 'ETH'],
    "MNGO": ['ETH', 'USDT'],
    "POWR": ['ETH', 'BTC', 'USDT'],
    "FINE": ['ETH', 'USDT'],
    "FILDA": ['ETH', 'USDT'],
    "GCOIN": ['USDT'],
    "NPT": ['USDT'],
    "PMON": ['ETH', 'USDT'],
    "NEAR": ['ETH', 'USDT'],
    "IOEN": ['USDT', 'ETH'],
    "BAGS": ['USDT', 'ETH'],
    "SDN": ['USDT', 'BTC', 'ETH'],
    "KAVA3S": ['USDT'],
    "PROM": ['USDT', 'ETH'],
    "SOP": ['ETH', 'USDT'],
    "SENSO": ['ETH', 'USDT'],
    "FDT": ['USDT'],
    "ALD": ['ETH', 'USDT'],
    "DUCK": ['USDT', 'ETH'],
    "HIT": ['USDT', 'ETH'],
    "GNO": ['ETH', 'USDT'],
    "FX": ['ETH', 'USDT'],
    "XTAG": ['ETH', 'USDT'],
    "TRB": ['ETH', 'USDT'],
    "IHT": ['USDT', 'ETH'],
    "LINK3S": ['USDT'],
    "XYO": ['ETH', 'USDT'],
    "DOMI": ['USDT'],
    "HOPR": ['USDT', 'ETH'],
    "ZOON": ['USDT'],
    "OMG3L": ['USDT'],
    "KAI": ['USDT'],
    "BFT": ['ETH', 'USDT'],
    "BLY": ['USDT', 'BTC'],
    "HECH": ['USDT'],
    "HE": ['USDT'],
    "VALUE": ['ETH', 'USDT'],
    "TRVL": ['BTC', 'USDT'],
    "VOXEL": ['USDT'],
    "PET": ['BTC', 'USDT', 'ETH'],
    "IPAD": ['USDT'],
    "OCEAN": ['USDT'],
    "DOGNFT": ['USDT', 'ETH'],
    "EOSBEAR": ['USDT'],
    "DMLG": ['USDT'],
    "GAL3S": ['USDT'],
    "COFIX": ['USDT'],
    "ETHF": ['USDT'],
    "VRX": ['ETH', 'USDT'],
    "KNIGHT": ['USDT'],
    "SRM": ['ETH', 'USDT'],
    "METAL": ['USDT'],
    "FIRE": ['USDT', 'ETH'],
    "PBTC35A": ['ETH', 'USDT'],
    "FRA": ['ETH', 'USDT'],
    "EPIK": ['USDT'],
    "TBTC": ['USDT', 'ETH'],
    "ADA": ['USDT', 'BTC'],
    "SWASH": ['USDT'],
    "BRY": ['USDT', 'ETH'],
    "DMS": ['ETH', 'USDT'],
    "TXT": ['ETH', 'USDT'],
    "MTA": ['USDT', 'ETH'],
    "NEXO": ['USDT', 'ETH'],
    "EDR": ['ETH'],
    "WRX": ['ETH', 'USDT'],
    "SQUID": ['USDT', 'ETH'],
    "XRP3S": ['USDT'],
    "STRAX": ['USDT', 'BTC', 'ETH'],
    "OXY": ['USDT', 'ETH'],
    "DNT": ['ETH'],
    "UNDEAD": ['USDT'],
    "QSP": ['ETH', 'USDT'],
    "BUSY": ['USDT'],
    "CITY": ['USDT'],
    "OOE": ['USDT', 'ETH'],
    "MOMA": ['USDT', 'ETH'],
    "DOP": ['USDT'],
    "WRT": ['USDT'],
    "DFA": ['USDT'],
    "CELR": ['USDT', 'ETH'],
    "PSG": ['ETH', 'USDT'],
    "WBTC": ['USDT', 'BTC'],
    "GSPI": ['ETH', 'USDT'],
    "BAO": ['ETH', 'USDT'],
    "JASMY": ['USDT', 'ETH'],
    "WALLET": ['USDT'],
    "HBAR3L": ['USDT'],
    "JOE": ['ETH', 'USDT'],
    "VEMP": ['USDT'],
    "ZSC": ['ETH', 'USDT'],
    "UNI3S": ['USDT'],
    "ORCA": ['USDT'],
    "XCUR": ['ETH', 'USDT'],
    "OXT": ['USDT', 'ETH'],
    "VXT": ['USDT'],
    "TRADE": ['USDT'],
    "DOG": ['USDT', 'ETH'],
    "FIRO": ['USDT'],
    "QTUM3L": ['USDT'],
    "SSV": ['ETH', 'BTC', 'USDT'],
    "SAUBER": ['USDT'],
    "LST": ['ETH'],
    "INSTAR": ['ETH'],
    "ESG": ['USDT'],
    "CAKE3S": ['USDT'],
    "OPUL": ['USDT', 'ETH'],
    "KEEP": ['ETH', 'USDT'],
    "RFT": ['USDT'],
    "PST": ['USDT', 'ETH'],
    "XPRESS": ['USDT'],
    "FXF": ['ETH', 'USDT'],
    "GEL": ['ETH', 'USDT'],
    "NAX": ['ETH', 'USDT'],
    "RARI": ['USDT', 'ETH'],
    "KASTA": ['USDT'],
    "EPX": ['USDT', 'ETH'],
    "SLP": ['ETH', 'USDT'],
    "AKT": ['ETH', 'USDT'],
    "LDO": ['USDT', 'ETH'],
    "CWAR": ['USDT', 'ETH'],
    "LINK5L": ['USDT'],
    "RIF": ['USDT', 'ETH'],
    "MTRG": ['USDT'],
    "TRA": ['USDT'],
    "BCX": ['BTC', 'USDT'],
    "EDG": ['ETH', 'USDT'],
    "DFND": ['USDT'],
    "MINI": ['USDT', 'ETH'],
    "XEC3L": ['USDT'],
    "KAP": ['USDT'],
    "IDEX": ['USDT', 'ETH'],
    "DYP": ['USDT', 'ETH'],
    "CRP": ['ETH', 'USDT'],
    "CTX": ['USDT'],
    "YFX": ['USDT'],
    "XRP": ['BTC', 'USDT'],
    "DOGGY": ['USDT'],
    "ELF": ['ETH', 'USDT'],
    "XIL": ['USDT'],
    "ARV": ['USDT'],
    "NMT": ['USDT', 'ETH'],
    "UNI": ['USDT', 'ETH'],
    "GENS": ['USDT'],
    "DIS": ['ETH', 'USDT'],
    "BAL3S": ['USDT'],
    "POLYPAD": ['USDT'],
    "STND": ['ETH', 'USDT'],
    "POPK": ['USDT'],
    "API33L": ['USDT'],
    "TORN": ['USDT', 'ETH'],
    "WAR": ['USDT', 'ETH'],
    "MFOOTBALL": ['USDT'],
    "APT": ['USDT', 'BTC', 'ETH'],
    "BCN": ['USDT', 'BTC'],
    "MUSE": ['ETH', 'USDT'],
    "EOS3S": ['USDT'],
    "VVS": ['USDT'],
    "HIVE": ['USDT'],
    "L3P": ['USDT', 'ETH'],
    "VATRENI": ['USDT'],
    "UBXS": ['USDT'],
    "DORA": ['USDT', 'ETH'],
    "VEE": ['USDT'],
    "FNF": ['USDT'],
    "DCRN": ['USDT'],
    "TCP": ['ETH', 'USDT'],
    "LINK3L": ['USDT'],
    "KPAD": ['ETH', 'USDT'],
    "TITA": ['ETH', 'USDT'],
    "OLAND": ['USDT'],
    "PERL": ['ETH', 'USDT'],
    "SAND": ['USDT', 'ETH'],
    "ERN": ['ETH', 'USDT'],
    "WAM": ['USDT'],
    "SYN": ['USDT', 'ETH'],
    "MTS": ['ETH', 'USDT'],
    "FDC": ['USDT'],
    "FITFI3L": ['USDT'],
    "CUSD": ['ETH', 'USDT'],
    "EWT": ['USDT', 'ETH'],
    "T": ['ETH', 'USDT'],
    "ORN": ['ETH', 'USDT'],
    "LAVA": ['USDT', 'ETH'],
    "METALDR": ['USDT'],
    "JST3S": ['USDT'],
    "IP3": ['USDT'],
    "CTSI": ['USDT'],
    "SIDUS": ['USDT'],
    "GEAR": ['USDT'],
    "REEF": ['ETH', 'USDT'],
    "INSUR": ['ETH', 'USDT'],
    "SERO": ['ETH', 'USDT'],
    "EUL": ['USDT'],
    "FUEL": ['USDT', 'ETH'],
    "GALA5S": ['USDT'],
    "HNT": ['USDT', 'ETH'],
    "DF": ['ETH', 'USDT'],
    "QKC": ['BTC', 'USDT', 'ETH'],
    "ORB": ['USDT'],
    "LIT": ['USDT', 'ETH'],
    "SERO3L": ['USDT'],
    "SLRS": ['USDT', 'ETH'],
    "KAVA3L": ['USDT'],
    "LRC3S": ['USDT'],
    "RBN": ['ETH', 'USDT'],
    "LAMB": ['ETH', 'USDT'],
    "ABBC": ['USDT'],
    "CWEB": ['USDT'],
    "STAR": ['USDT', 'ETH'],
    "CFX3L": ['USDT'],
    "OPA": ['USDT'],
    "YAM": ['ETH', 'USDT'],
    "CEEK": ['USDT', 'ETH'],
    "CTRC": ['USDT'],
    "DEPO": ['USDT'],
    "KIMCHI": ['USDT', 'ETH'],
    "BAKED": ['USDT', 'ETH'],
    "VIDYX": ['ETH', 'USDT'],
    "SLND": ['USDT', 'ETH'],
    "SKL3S": ['USDT'],
    "BEPRO": ['USDT', 'ETH'],
    "JGN": ['USDT', 'ETH'],
    "SPS": ['ETH', 'USDT'],
    "MGG": ['USDT'],
    "UMEE": ['USDT'],
    "FIWA": ['USDT'],
    "TARI": ['USDT'],
    "FLURRY": ['USDT'],
    "ACH": ['USDT', 'ETH'],
    "WNCG": ['USDT', 'BTC'],
    "BTO": ['ETH', 'USDT'],
    "FRM": ['USDT'],
    "KFT": ['USDT', 'ETH'],
    "KLO": ['USDT'],
    "ORT": ['USDT'],
    "GSE": ['USDT', 'ETH'],
    "LIQ": ['USDT'],
    "FCD": ['USDT'],
    "CVP": ['USDT', 'ETH'],
    "AAVE": ['ETH', 'USDT'],
    "RED": ['ETH', 'USDT'],
    "SC": ['ETH', 'USDT'],
    "MIST": ['USDT', 'ETH'],
    "AZY": ['USDT'],
    "OMG": ['USDT', 'ETH', 'BTC'],
    "HBAR3S": ['USDT'],
    "EMPIRE": ['USDT', 'ETH'],
    "BLACK": ['USDT', 'ETH'],
    "THETA3L": ['USDT'],
    "MESA": ['ETH', 'USDT'],
    "A5T": ['ETH', 'USDT'],
    "BBANK": ['BTC', 'ETH', 'USDT'],
    "WAXP": ['ETH', 'USDT'],
    "REM": ['USDT', 'ETH'],
    "XEM": ['BTC', 'USDT', 'ETH'],
    "RENBTC": ['USDT', 'BTC'],
    "HNS": ['USDT', 'BTC'],
    "MOVEZ": ['USDT'],
    "ORION": ['USDT'],
    "DOGE3S": ['USDT'],
    "RLY": ['USDT', 'ETH'],
    "MLN": ['ETH', 'USDT'],
    "ZKT": ['USDT'],
    "HAI": ['USDT', 'ETH'],
    "AMP": ['ETH', 'USDT'],
    "MPH": ['ETH', 'USDT'],
    "HIGH": ['USDT'],
    "SB": ['USDT'],
    "BNTY": ['USDT', 'ETH'],
    "ARMOR": ['ETH', 'USDT'],
    "AR3L": ['USDT'],
    "QTCON": ['USDT'],
    "KBD": ['USDT'],
    "GFI": ['USDT', 'ETH'],
    "WSIENNA": ['USDT'],
    "TOTM": ['USDT'],
    "EGAME": ['USDT'],
    "FIDA": ['ETH', 'USDT'],
    "LON3S": ['USDT'],
    "SMTY": ['ETH', 'USDT'],
    "NORD": ['ETH', 'USDT'],
    "PNL": ['USDT', 'ETH'],
    "POLS": ['USDT'],
    "SFI": ['USDT', 'ETH'],
    "BDT": ['ETH', 'USDT'],
    "RAGE": ['USDT'],
    "CUP": ['USDT'],
    "KDA": ['BTC', 'USDT'],
    "HOT": ['USDT', 'ETH'],
    "NAOS": ['BTC', 'ETH', 'USDT'],
    "MKR3S": ['USDT'],
    "MDX": ['ETH', 'USDT'],
    "BLOK": ['ETH', 'USDT'],
    "PHA": ['USDT'],
    "BCD": ['USDT', 'BTC'],
    "FEI": ['USDT', 'ETH'],
    "BBK": ['ETH'],
    "WAGYU": ['USDT', 'ETH'],
    "DKS": ['USDT'],
    "CLO": ['USDT'],
    "MBS": ['ETH', 'USDT'],
    "HFT": ['USDT', 'ETH'],
    "GAS": ['BTC', 'USDT'],
    "ATEAM": ['USDT'],
    "PRT": ['USDT', 'ETH'],
    "TAKI": ['USDT'],
    "BSW3L": ['USDT'],
    "POLI": ['USDT'],
    "KEX": ['USDT', 'ETH'],
    "ICONS": ['ETH', 'USDT'],
    "ALGO3L": ['USDT'],
    "TNC": ['BTC', 'ETH', 'USDT'],
    "MARS": ['USDT', 'ETH'],
    "RAD": ['ETH', 'USDT'],
    "PIT": ['USDT'],
    "SPEX": ['USDT'],
    "DEHUB": ['USDT'],
    "FET": ['USDT', 'ETH'],
    "LEO": ['USDT', 'BTC'],
    "XPR": ['ETH', 'USDT'],
    "LIT3L": ['USDT'],
    "HAO": ['USDT', 'ETH', 'BTC'],
    "FLY": ['USDT'],
    "NAFT": ['USDT'],
    "PTS": ['USDT'],
    "MATIC": ['ETH', 'USDT'],
    "AGLD": ['USDT', 'ETH'],
    "PRISM": ['USDT', 'ETH'],
    "EOS3L": ['USDT'],
    "SWOP": ['USDT', 'ETH'],
    "POOL": ['ETH', 'USDT'],
    "DPET": ['ETH', 'USDT'],
    "ROOM": ['USDT', 'ETH'],
    "MENGO": ['USDT'],
    "IOST3S": ['USDT'],
    "MBL": ['ETH', 'USDT'],
    "88MPH": ['USDT', 'ETH'],
    "BTS": ['USDT', 'BTC'],
    "NEAR3S": ['USDT'],
    "CTT": ['USDT'],
    "CLH": ['USDT'],
    "ROSE": ['USDT', 'ETH'],
    "NGL": ['USDT'],
    "SLNV2": ['ETH', 'USDT'],
    "KEY": ['USDT', 'ETH'],
    "STX": ['USDT', 'ETH'],
    "BTM": ['ETH', 'BTC', 'USDT'],
    "AUCTION": ['ETH', 'USDT'],
    "ASTR3S": ['USDT'],
    "XED": ['USDT', 'ETH'],
    "GDAO": ['USDT', 'ETH'],
    "TOKAU": ['USDT'],
    "YFI3L": ['USDT'],
    "STOX": ['USDT', 'ETH'],
    "TAUR": ['USDT'],
    "WGRT": ['USDT'],
    "YLD": ['USDT'],
    "SAITO": ['USDT'],
    "ADEL": ['ETH', 'USDT'],
    "AMKT": ['USDT'],
    "FXS": ['ETH', 'USDT'],
    "CVAULTCORE": ['ETH', 'USDT'],
    "QTC": ['USDT', 'ETH'],
    "SAKE": ['ETH', 'USDT'],
    "SENC": ['USDT', 'ETH'],
    "WZRD": ['USDT'],
    "OKB3S": ['USDT'],
    "PIAS": ['USDT'],
    "SUSHI": ['USDT', 'ETH'],
    "MM": ['ETH', 'USDT'],
    "TONCOIN": ['ETH', 'USDT'],
    "UNI5S": ['USDT'],
    "CIRUS": ['USDT'],
    "CS": ['ETH', 'USDT'],
    "SNX3L": ['USDT'],
    "BTCBULL": ['USDT'],
    "ATLAS": ['USDT'],
    "LTC5S": ['USDT'],
    "WEX": ['USDT'],
    "GUM": ['USDT'],
    "DEXE": ['ETH', 'USDT'],
    "GRT3S": ['USDT'],
    "MASK3L": ['USDT'],
    "FLM": ['USDT', 'ETH'],
    "KSM": ['USDT'],
    "ALAYA": ['ETH', 'USDT'],
    "POLC": ['USDT', 'ETH'],
    "GALA3S": ['USDT'],
    "PING": ['USDT'],
    "BSV": ['USDT', 'BTC'],
    "ESD": ['ETH', 'USDT'],
    "FIU": ['USDT'],
    "SBR": ['ETH', 'USDT'],
    "PRMX": ['USDT'],
    "FORT": ['USDT'],
    "HT3S": ['USDT'],
    "HPB": ['ETH', 'USDT'],
    "WOZX": ['ETH', 'USDT'],
    "XDC": ['USDT', 'ETH'],
    "AM": ['USDT'],
    "ONG": ['USDT', 'ETH'],
    "JST": ['USDT'],
    "FAN": ['ETH', 'USDT'],
    "DHX": ['USDT'],
    "FUN": ['ETH', 'USDT'],
    "PCNT": ['USDT', 'ETH'],
    "COMP": ['USDT'],
    "BTC3S": ['USDT'],
    "ANKR": ['USDT'],
    "MULTI": ['ETH', 'USDT'],
    "FCON": ['USDT'],
    "DAR": ['USDT', 'ETH'],
    "C98": ['USDT', 'BTC'],
    "BMI": ['ETH', 'USDT'],
    "SNX": ['USDT'],
    "JASMY3S": ['USDT'],
    "LOKA3S": ['USDT'],
    "TIMECHRONO": ['ETH', 'USDT'],
    "LEMO": ['ETH', 'USDT'],
    "XOR": ['USDT', 'ETH'],
    "KIF": ['USDT', 'ETH'],
    "ONE3L": ['USDT'],
    "RAZE": ['USDT', 'ETH'],
    "HERA": ['USDT'],
    "HC": ['USDT', 'ETH', 'BTC'],
    "AXS3S": ['USDT'],
    "AE": ['USDT', 'BTC', 'ETH'],
    "TCT": ['USDT', 'ETH'],
    "ATM": ['USDT'],
    "RATING": ['USDT', 'ETH'],
    "KLAY3L": ['USDT'],
    "FOREX": ['USDT', 'ETH'],
    "GXS": ['BTC', 'USDT'],
    "OLYMPUS": ['USDT'],
    "ARCX": ['USDT', 'ETH'],
    "K21": ['USDT', 'ETH'],
    "GAIA": ['USDT'],
    "NAP": ['USDT'],
    "PUMLX": ['USDT'],
    "NSBT": ['BTC', 'USDT', 'ETH'],
    "REVV": ['ETH', 'USDT'],
    "MODA": ['ETH', 'USDT'],
    "BFC": ['USDT', 'ETH'],
    "ITRUMP": ['USDT'],
    "BAND": ['USDT', 'ETH'],
    "KNOT": ['USDT'],
    "VOLT": ['USDT'],
    "PNK": ['USDT', 'ETH'],
    "SKILL": ['USDT', 'ETH'],
    "RNDX": ['USDT'],
    "DPR": ['USDT', 'ETH'],
    "CZZ": ['USDT'],
    "BTC5L": ['USDT'],
    "UMX": ['ETH', 'USDT'],
    "SCCP": ['USDT'],
    "NXD": ['USDT'],
    "XMR": ['USDT', 'BTC'],
    "CELT": ['USDT'],
    "DUST": ['USDT'],
    "PWAR": ['ETH', 'USDT'],
    "CUDOS": ['USDT'],
    "DX": ['ETH', 'USDT'],
    "WWY": ['USDT'],
    "MAPS": ['USDT', 'ETH'],
    "HELLO": ['USDT'],
    "IDEA": ['USDT'],
    "PERA": ['USDT'],
    "HIFI": ['USDT', 'ETH'],
    "SXP": ['ETH', 'USDT'],
    "NANO": ['BTC', 'USDT'],
    "USDG": ['USDT'],
    "TWT": ['ETH', 'USDT'],
    "FRONT": ['USDT', 'ETH'],
    "MITH": ['USDT', 'ETH'],
    "CONV": ['USDT', 'ETH'],
    "GOLDMINER": ['USDT'],
    "VLXPAD": ['USDT', 'ETH'],
    "DESO": ['USDT'],
    "MONS": ['USDT'],
    "BXH": ['ETH', 'USDT'],
    "LBLOCK": ['USDT'],
    "GRIN3L": ['USDT'],
    "NAS": ['USDT', 'ETH', 'BTC'],
    "ATP": ['USDT', 'ETH'],
    "FEG": ['USDT'],
    "IONX": ['ETH', 'USDT'],
    "GOB": ['USDT'],
    "ZCN": ['USDT', 'ETH'],
    "XLM": ['ETH', 'USDT', 'BTC'],
    "FODL": ['USDT', 'ETH'],
    "FST": ['ETH', 'USDT'],
    "CEUR": ['ETH', 'USDT'],
    "SHPING": ['USDT'],
    "CHNG": ['USDT', 'BTC'],
    "KTN": ['ETH', 'USDT'],
    "VRA": ['USDT', 'BTC'],
    "BEL": ['USDT', 'ETH'],
    "VTG": ['USDT'],
    "ONS": ['USDT', 'ETH'],
    "XTZ3L": ['USDT'],
    "ACX": ['USDT'],
    "SUP": ['USDT'],
    "FEAR": ['USDT'],
    "OMI": ['USDT', 'ETH'],
    "KYL": ['USDT', 'ETH'],
    "LAT": ['USDT'],
    "GT": ['ETH', 'USDT', 'BTC'],
    "ETHW": ['ETH', 'USDT'],
    "ORAI": ['ETH', 'USDT'],
    "YOOSHI": ['USDT'],
    "MRCH": ['ETH', 'USDT'],
    "UTK": ['ETH', 'USDT'],
    "HEART": ['USDT'],
    "NIFTSY": ['USDT'],
    "EVRY": ['USDT'],
    "ATA": ['USDT', 'ETH'],
    "DYDX": ['USDT', 'ETH'],
    "PLY": ['ETH'],
    "BURP": ['ETH', 'USDT'],
    "PI": ['BTC', 'USDT'],
    "ASTRA": ['USDT'],
    "QLC": ['ETH', 'USDT', 'BTC'],
    "CKB": ['USDT', 'ETH', 'BTC'],
    "SRG": ['USDT'],
    "ARES": ['ETH', 'USDT'],
    "DFY": ['ETH', 'USDT'],
    "IAZUKI": ['USDT'],
    "XY": ['USDT'],
    "KNC": ['USDT', 'ETH'],
    "BSW": ['USDT'],
    "VERA": ['USDT', 'ETH'],
    "RFUEL": ['USDT'],
    "ROOBEE": ['USDT'],
    "SKEB": ['USDT'],
    "BCUG": ['USDT', 'ETH'],
    "OST": ['USDT', 'ETH'],
    "AVAX3L": ['USDT'],
    "COTI3S": ['USDT'],
    "IMX3L": ['USDT'],
    "LRN": ['USDT', 'ETH'],
    "HGET": ['ETH', 'USDT'],
    "SAITAMA": ['USDT'],
    "ENJ3S": ['USDT'],
    "GOF": ['USDT'],
    "BSV3L": ['USDT'],
    "MNY": ['USDT'],
    "RACA3L": ['USDT'],
    "YFII": ['USDT', 'ETH'],
    "SNFT1": ['USDT'],
    "BTM3L": ['USDT'],
    "VELO": ['USDT', 'ETH'],
    "ATOM3L": ['USDT'],
    "SPAY": ['ETH', 'USDT'],
    "HBAR": ['USDT'],
    "MXC": ['ETH', 'BTC', 'USDT'],
    "MNDE": ['USDT'],
    "LN": ['BTC', 'USDT'],
    "DAG": ['ETH', 'BTC', 'USDT'],
    "LINK": ['ETH', 'USDT'],
    "FLR": ['USDT'],
    "BEYOND": ['USDT'],
    "CORN": ['USDT'],
    "PENDLE": ['ETH', 'USDT'],
    "UNN": ['USDT', 'ETH'],
    "IZI": ['ETH', 'USDT'],
    "MLK": ['USDT'],
    "KRL": ['USDT'],
    "DREP": ['ETH', 'USDT'],
    "SHR": ['USDT', 'ETH'],
    "FAME": ['USDT'],
    "C983S": ['USDT'],
    "EDEN": ['USDT', 'ETH'],
    "WIKEN": ['USDT', 'BTC'],
    "CREDIT": ['ETH', 'USDT'],
    "LUNC": ['USDT'],
    "CRTS": ['USDT', 'ETH'],
    "LEDU": ['ETH', 'BTC'],
    "WNDR": ['USDT'],
    "FRR": ['USDT'],
    "QTUM3S": ['USDT'],
    "ELU": ['USDT'],
    "STR": ['USDT', 'ETH'],
    "D2T": ['USDT'],
    "WEMIX": ['USDT', 'ETH'],
    "LOOKS3S": ['USDT'],
    "PIXEL": ['USDT'],
    "MIMIR": ['ETH', 'USDT'],
    "NSURE": ['ETH', 'USDT'],
    "ZIL3L": ['USDT'],
    "GOFX": ['USDT'],
    "BORING": ['ETH', 'USDT'],
    "ANC3L": ['USDT'],
    "DOGGO": ['USDT'],
    "ARPA": ['USDT', 'ETH'],
    "FTI": ['ETH', 'USDT'],
    "LINK5S": ['USDT'],
    "MATTER": ['USDT', 'ETH'],
    "ANGLE": ['USDT'],
    "RACA": ['USDT'],
    "AVAX": ['ETH', 'USDT'],
    "BICO": ['ETH', 'USDT'],
    "CNNS": ['USDT', 'ETH'],
    "CART": ['ETH', 'USDT'],
    "XVG": ['USDT', 'BTC'],
    "CATE": ['USDT'],
    "ETERNAL": ['USDT'],
    "CRV": ['ETH', 'USDT', 'BTC'],
    "ADA3S": ['USDT'],
    "PBX": ['USDT', 'ETH'],
    "WIT": ['ETH', 'BTC', 'USDT'],
    "TDROP": ['USDT'],
    "TIFI": ['USDT'],
    "CEL": ['ETH', 'USDT'],
    "VIDY": ['USDT', 'ETH'],
    "RICE": ['ETH', 'USDT'],
    "ASR": ['USDT'],
    "OCC": ['USDT'],
    "NBOT": ['USDT', 'ETH'],
    "ORC": ['USDT'],
    "IHC": ['USDT'],
    "UMB": ['ETH', 'USDT'],
    "OOKI": ['USDT'],
    "ASK": ['USDT'],
    "GTH": ['USDT', 'ETH'],
    "EOS5S": ['USDT'],
    "LEV": ['USDT'],
    "NCT": ['ETH', 'USDT'],
    "BTRST": ['USDT', 'ETH'],
    "YGG": ['USDT', 'ETH'],
    "LABS": ['ETH', 'USDT'],
    "POLK": ['USDT', 'ETH'],
    "BORA": ['USDT', 'ETH'],
    "BRISE": ['USDT'],
    "ONT": ['ETH', 'USDT'],
    "EFI": ['USDT', 'ETH'],
    "JFI": ['USDT'],
    "SOL3L": ['USDT'],
    "EZ": ['USDT', 'ETH'],
    "SASHIMI": ['USDT', 'ETH'],
    "HORD": ['USDT', 'ETH'],
    "BZZ3S": ['USDT'],
    "ALICE3L": ['USDT'],
    "SQUIDGROW": ['USDT'],
    "JST3L": ['USDT'],
    "PROS": ['ETH', 'USDT'],
    "BKC": ['USDT'],
    "STG": ['ETH', 'USDT'],
    "ZONE": ['USDT'],
    "DKA": ['ETH', 'USDT'],
    "XVS": ['ETH', 'USDT'],
    "RFR": ['ETH', 'USDT'],
    "RUNE": ['ETH', 'USDT'],
    "CFG": ['BTC', 'USDT'],
    "SPELLFIRE": ['USDT'],
    "TMT": ['ETH'],
    "ALICE3S": ['USDT'],
    "RFOX": ['USDT', 'ETH'],
    "OLY": ['USDT'],
    "TSL": ['USDT'],
    "APE3L": ['USDT'],
    "ROSE3L": ['USDT'],
    "IOI": ['USDT'],
    "COCOS": ['USDT'],
    "LGCY": ['USDT'],
    "ESS": ['ETH', 'USDT'],
    "APT3L": ['USDT'],
    "SFUND": ['USDT'],
    "ZPT": ['BTC', 'USDT', 'ETH'],
    "GGM": ['USDT'],
    "KST": ['ETH', 'USDT'],
    "HSC": ['USDT', 'ETH'],
    "ZLW": ['USDT', 'ETH'],
    "AKITA": ['USDT'],
    "QI": ['ETH', 'USDT'],
    "SNX3S": ['USDT'],
    "SCY": ['ETH', 'USDT'],
    "SANDWICH": ['USDT'],
    "DERC": ['USDT'],
    "WOO3L": ['USDT'],
    "GDT": ['USDT', 'ETH'],
    "ASS": ['USDT'],
    "CREAM": ['ETH', 'USDT'],
    "SCNSOL": ['ETH', 'USDT'],
    "TRX3S": ['USDT'],
    "UNO": ['USDT', 'ETH'],
    "CRO3S": ['USDT'],
    "SENATE": ['USDT'],
    "OP3S": ['USDT'],
    "UMA": ['USDT'],
    "BZZ": ['ETH', 'USDT'],
    "EURT": ['USDT'],
    "BZRX": ['USDT'],
    "PHM": ['USDT'],
    "COMBO": ['USDT', 'ETH'],
    "EVER": ['USDT'],
    "SHOE": ['USDT'],
    "RAMP": ['USDT'],
    "PYM": ['USDT'],
    "KMON": ['USDT'],
    "APYS": ['ETH', 'USDT'],
    "PICKLE": ['USDT', 'ETH'],
    "POLYDOGE": ['USDT'],
    "NFTD": ['USDT'],
    "BNB": ['BTC', 'USDT'],
    "GMAT": ['ETH', 'USDT'],
    "TLM": ['USDT', 'ETH'],
    "MKR3L": ['USDT'],
    "NOS": ['USDT', 'ETH'],
    "DXCT": ['USDT', 'ETH'],
    "TIME": ['USDT', 'ETH'],
    "KART": ['USDT'],
    "REAL": ['USDT'],
    "LOON": ['ETH', 'USDT'],
    "DNXC": ['USDT'],
    "NEAR3L": ['USDT'],
    "CFI": ['ETH', 'USDT'],
    "ICP3S": ['USDT'],
    "RING": ['ETH', 'USDT'],
    "NEO3L": ['USDT'],
    "KP3R": ['ETH', 'USDT'],
    "BEEFI": ['USDT', 'ETH'],
    "B3X": ['USDT'],
    "LOKA": ['USDT', 'ETH'],
    "SBTC": ['BTC', 'USDT'],
    "PERI": ['USDT'],
    "GMT3S": ['USDT'],
    "LOCG": ['USDT', 'ETH'],
    "APN": ['ETH', 'USDT'],
    "MYRA": ['USDT'],
    "LIEN": ['USDT', 'ETH'],
    "FAR": ['USDT', 'ETH'],
    "EGLD3S": ['USDT'],
    "SWAP": ['USDT', 'ETH'],
    "MDT": ['ETH', 'BTC', 'USDT'],
    "MOT": ['USDT'],
    "DMTR": ['USDT'],
    "RITE": ['USDT'],
    "TRR": ['USDT'],
    "SALT": ['USDT', 'ETH'],
    "ZIL": ['USDT', 'ETH'],
    "LEASH": ['USDT', 'ETH'],
    "BABI": ['USDT'],
    "TTT": ['USDT'],
    "BTG": ['USDT', 'BTC'],
    "OPIUM": ['USDT', 'ETH'],
    "OHM": ['USDT', 'ETH'],
    "SWTH": ['ETH', 'USDT'],
    "BSCPAD": ['USDT', 'ETH'],
    "MC": ['ETH', 'USDT'],
    "GARI": ['USDT', 'ETH'],
    "MOVR": ['ETH', 'USDT'],
    "SHFT": ['ETH', 'USDT'],
    "KSM3L": ['USDT'],
    "MCO2": ['ETH', 'USDT'],
    "SCLP": ['USDT', 'ETH'],
    "MSU": ['USDT'],
    "KIBA": ['USDT'],
    "VSP": ['USDT', 'ETH'],
    "CRV3L": ['USDT'],
    "NFTY": ['ETH', 'USDT'],
    "CRAFT": ['USDT'],
    "MOO": ['USDT'],
    "ARNX": ['USDT', 'ETH'],
    "GLQ": ['ETH', 'USDT'],
    "ICX": ['USDT', 'ETH'],
    "LGX": ['USDT'],
    "XRD": ['ETH', 'USDT'],
    "CRU": ['USDT', 'ETH'],
    "MAHA": ['ETH', 'USDT'],
    "BCH5L": ['USDT'],
    "POR": ['USDT'],
    "VEGA": ['ETH', 'USDT'],
    "FLOW": ['USDT', 'ETH'],
    "SPELL": ['ETH', 'USDT'],
    "DERI": ['ETH', 'USDT'],
    "SEELE": ['USDT'],
    "UNFI": ['ETH', 'USDT'],
    "MMM": ['USDT'],
    "SONAR": ['ETH', 'USDT'],
    "IOTA": ['USDT', 'BTC'],
    "CSTR": ['ETH', 'USDT'],
    "IOST": ['BTC', 'USDT'],
    "CGG": ['ETH', 'USDT'],
    "IBFK": ['USDT'],
    "ALA": ['USDT'],
    "TOKE": ['USDT', 'ETH'],
    "OM": ['USDT', 'ETH'],
    "STOS": ['ETH', 'USDT'],
    "TTK": ['USDT'],
    "SFM": ['USDT'],
    "SKU": ['USDT'],
    "GALO": ['USDT'],
    "UNI5L": ['USDT'],
    "SNY": ['ETH', 'USDT'],
    "TEER": ['USDT'],
    "SHIP": ['ETH'],
    "ENNO": ['USDT'],
    "ONSTON": ['USDT'],
    "CRE8": ['USDT'],
    "AST": ['ETH', 'USDT'],
    "PHTR": ['USDT'],
    "XRP3L": ['USDT'],
    "ACH3S": ['USDT'],
    "ZRX": ['BTC', 'USDT', 'ETH'],
    "CTG": ['USDT'],
    "SHOPX": ['USDT', 'ETH'],
    "TROY": ['ETH', 'USDT'],
    "MINA": ['USDT', 'BTC'],
    "STARL": ['USDT'],
    "RIDE": ['USDT'],
    "LUFFY": ['USDT', 'ETH'],
    "SPFC": ['USDT'],
    "XTZ": ['ETH', 'USDT', 'BTC'],
    "RCN": ['USDT', 'ETH'],
    "NRV": ['ETH', 'USDT'],
    "FTM3L": ['USDT'],
    "BEAM3S": ['USDT'],
    "RANKER": ['USDT'],
    "IMPT": ['USDT'],
    "SKT": ['USDT'],
    "SOS": ['USDT'],
    "ETH2": ['ETH', 'USDT'],
    "BNT": ['ETH'],
    "UNQ": ['USDT'],
    "WILD": ['USDT'],
    "NOIA": ['ETH', 'USDT'],
    "INTER": ['USDT'],
    "EHASH": ['ETH', 'USDT'],
    "ETH3S": ['USDT'],
    "DOGEDASH": ['USDT', 'ETH'],
    "SUSD": ['USDT', 'ETH'],
    "ARRR": ['USDT', 'ETH'],
    "COS": ['USDT'],
    "SWAY": ['USDT'],
    "MOON": ['USDT'],
    "FTM3S": ['USDT'],
    "VR": ['USDT'],
    "IMX": ['USDT', 'ETH'],
    "CWS": ['ETH', 'USDT'],
    "GEM": ['ETH', 'USDT'],
    "LEMD": ['USDT', 'ETH'],
    "CRPT": ['USDT', 'ETH'],
    "AIOZ": ['ETH', 'USDT'],
    "OP": ['USDT', 'ETH'],
    "NU": ['USDT', 'ETH'],
    "STMX": ['ETH', 'USDT'],
    "MSOL": ['USDT', 'ETH'],
    "KINE": ['USDT', 'ETH'],
    "UPP": ['ETH'],
    "ZEN3L": ['USDT'],
    "NIFT": ['USDT'],
    "VISR": ['ETH', 'USDT'],
    "ASW": ['USDT'],
    "MONI": ['USDT'],
    "GTC": ['ETH', 'BTC', 'USDT'],
    "XCAD": ['USDT'],
    "ONT3S": ['USDT'],
    "GMPD": ['USDT'],
    "GOV": ['USDT'],
    "NAVI": ['USDT'],
    "UNI3L": ['USDT'],
    "ORBS": ['USDT', 'ETH'],
    "SXP3L": ['USDT'],
    "DRGN": ['USDT', 'ETH'],
    "LOWB": ['USDT'],
    "CRF": ['USDT', 'ETH'],
    "DDIM": ['ETH', 'USDT'],
    "GRBE": ['USDT'],
    "BSCS": ['USDT', 'ETH'],
    "ATMI": ['ETH'],
    "CHEQ": ['USDT'],
    "GOD": ['BTC', 'USDT'],
    "LPT": ['USDT', 'ETH'],
    "ONE": ['USDT'],
    "ETH": ['BTC', 'USDT'],
    "LION": ['USDT'],
    "WHALE": ['USDT'],
    "XMARK": ['USDT', 'ETH'],
    "UPI": ['USDT'],
    "KUMA": ['USDT'],
    "CHESS": ['USDT', 'ETH'],
    "POG": ['USDT'],
    "SPIRIT": ['USDT'],
    "ADD": ['ETH'],
    "INJ": ['USDT', 'ETH'],
    "XDEFI": ['USDT'],
    "CULT": ['USDT'],
    "TARA": ['BTC', 'USDT', 'ETH'],
    "DEUS": ['USDT'],
    "MIR": ['ETH', 'USDT'],
    "TULIP": ['USDT', 'ETH'],
    "SHI": ['USDT'],
    "HOTCROSS": ['USDT', 'ETH'],
    "FIL3S": ['USDT'],
    "SSX": ['USDT'],
    "SAFEMOON": ['USDT'],
    "DAL": ['USDT'],
    "ASTR3L": ['USDT'],
    "XEND": ['USDT', 'ETH'],
    "SOURCE": ['ETH', 'USDT'],
    "ORO": ['USDT'],
    "STN": ['ETH', 'USDT'],
    "BIFI": ['USDT', 'BTC'],
    "NFTB": ['USDT', 'ETH'],
    "RUFF": ['BTC', 'USDT', 'ETH'],
    "POND": ['ETH', 'USDT'],
    "CYS": ['ETH', 'USDT'],
    "BCMC": ['USDT'],
    "MBOX": ['ETH', 'USDT'],
    "RSV": ['USDT'],
    "CELO": ['USDT'],
    "KAVA": ['USDT'],
    "STRP": ['ETH', 'USDT'],
    "PAY": ['USDT', 'ETH', 'BTC'],
    "MER": ['USDT'],
    "BOX": ['USDT'],
    "GMT": ['USDT'],
    "CRE": ['USDT'],
    "ALN": ['ETH', 'USDT'],
    "ALPH": ['USDT'],
    "TALK": ['USDT'],
    "LAYER": ['ETH', 'USDT'],
    "WNZ": ['USDT'],
    "FORTH": ['ETH', 'USDT'],
    "TIPS": ['USDT', 'ETH'],
    "RDN": ['ETH', 'USDT'],
    "BYN": ['USDT', 'ETH'],
    "ARG": ['USDT'],
    "LUNR": ['USDT'],
    "ARGON": ['USDT', 'ETH'],
    "LOOKS": ['ETH', 'USDT'],
    "ODDZ": ['ETH', 'USDT'],
    "RDF": ['USDT'],
    "SAMO": ['USDT', 'ETH'],
    "COMP3L": ['USDT'],
    "BIN": ['USDT', 'ETH'],
    "RBLS": ['USDT'],
    "BAMBOO": ['USDT'],
    "NEO": ['BTC', 'USDT'],
    "NIM": ['USDT'],
    "SUSHI3L": ['USDT'],
    "MATCH": ['USDT'],
    "RARE": ['ETH', 'USDT'],
    "BONDLY": ['USDT', 'ETH'],
    "LTC": ['USDT', 'BTC'],
    "AUTO": ['ETH', 'USDT'],
    "LUNCH": ['USDT'],
    "AIR": ['USDT'],
    "MOOV": ['USDT'],
    "ASD": ['USDT'],
    "MINA3S": ['USDT'],
    "PPS": ['USDT'],
    "CSPR": ['USDT', 'ETH'],
    "RVC": ['USDT'],
    "TOMS": ['USDT'],
    "STEEM": ['USDT'],
    "BITCI": ['USDT'],
    "FLOKI": ['USDT'],
    "LEVER": ['USDT'],
    "SOL": ['USDT'],
    "DOGE": ['BTC', 'USDT'],
    "LUNA": ['USDT', 'ETH'],
    "STEP": ['ETH', 'USDT'],
    "SUNNY": ['ETH', 'USDT'],
    "REVO": ['ETH', 'USDT', 'BTC'],
    "PIG": ['USDT'],
    "CHZ": ['ETH', 'USDT'],
    "CLV": ['USDT', 'ETH'],
    "ITGR": ['ETH', 'USDT'],
    "HOGE": ['USDT'],
    "NEBL": ['USDT'],
    "ARPA3S": ['USDT'],
    "RAM": ['USDT'],
    "XMC": ['USDT', 'BTC'],
    "HYVE": ['USDT', 'ETH'],
    "AURORA": ['USDT', 'ETH'],
    "DARK": ['USDT'],
    "YIELD": ['USDT', 'ETH'],
    "BACON": ['USDT'],
    "AXIS": ['USDT', 'ETH'],
    "ATS": ['USDT'],
    "EMON": ['USDT'],
    "VAI": ['USDT'],
    "THETA": ['USDT', 'ETH'],
    "HEGIC": ['USDT', 'ETH'],
    "DEBT": ['USDT'],
    "RPL": ['USDT'],
    "CAPS": ['USDT'],
    "OGN": ['USDT', 'ETH'],
    "DENT": ['USDT', 'ETH'],
    "NRFB": ['ETH', 'USDT'],
    "BNB3L": ['USDT'],
    "MLS": ['USDT'],
    "SVT": ['USDT', 'ETH'],
    "XAVA": ['USDT'],
    "CNAME": ['USDT'],
    "AXS5S": ['USDT'],
    "OAS": ['USDT'],
    "GLM": ['ETH', 'USDT'],
    "HMT": ['USDT', 'ETH'],
    "AZERO": ['USDT'],
    "HDV": ['USDT'],
    "NODL": ['USDT'],
    "ZODI": ['USDT', 'ETH'],
    "PEOPLE3S": ['USDT'],
    "SLICE": ['ETH', 'USDT'],
    "MOB": ['ETH', 'USDT'],
    "ENS": ['USDT', 'ETH'],
    "WINGS": ['ETH', 'USDT'],
    "SWRV": ['ETH', 'USDT'],
    "AMPL3L": ['USDT'],
    "GF": ['ETH', 'USDT'],
    "BOA": ['USDT'],
    "PORTO": ['USDT'],
    "PSP": ['USDT', 'ETH'],
    "XWG": ['USDT'],
    "MTG": ['USDT'],
    "BIFIF": ['USDT', 'ETH'],
    "WELL": ['USDT'],
    "FREE": ['USDT'],
    "FPFT": ['USDT'],
    "ALU": ['USDT', 'ETH'],
    "SOLR": ['USDT', 'ETH'],
    "POLY": ['ETH', 'USDT'],
    "ETC3L": ['USDT'],
    "KMA": ['USDT'],
    "WZM": ['USDT'],
    "T23": ['USDT'],
    "ADP": ['USDT', 'ETH'],
    "HAPI": ['USDT'],
    "SOV": ['BTC', 'USDT'],
    "ZIG": ['USDT'],
    "BOBA": ['USDT', 'ETH'],
    "UFO": ['USDT'],
    "WIN": ['USDT'],
    "EPK": ['USDT'],
    "BTC": ['USDT'],
    "CHO": ['USDT'],
    "KGC": ['USDT'],
    "IQ": ['ETH'],
    "MTR": ['USDT'],
    "ASTR": ['USDT', 'ETH', 'BTC'],
    "COOK": ['ETH', 'USDT'],
    "XDB": ['USDT'],
    "FROG": ['USDT', 'ETH'],
    "CCAR": ['USDT'],
    "ONX": ['USDT', 'ETH'],
    "ITAMCUBE": ['USDT'],
    "LINA": ['ETH', 'USDT'],
    "ING": ['USDT'],
    "MAT": ['USDT', 'ETH'],
    "GTO": ['USDT'],
    "AME": ['USDT', 'ETH'],
    "GOLD": ['USDT'],
    "BSV5S": ['USDT'],
    "GZONE": ['USDT', 'ETH'],
    "NIIFI": ['USDT'],
    "COMP3S": ['USDT'],
    "ULU": ['ETH', 'USDT'],
    "ZEN": ['USDT'],
    "MANA3L": ['USDT'],
    "CTI": ['USDT', 'ETH'],
    "1ART": ['USDT'],
    "NBP": ['ETH', 'USDT'],
    "YIN": ['USDT', 'ETH'],
    "GALFAN": ['USDT'],
    "CHR": ['USDT', 'ETH'],
    "BANK": ['USDT', 'ETH'],
    "BEAM3L": ['USDT'],
    "GST": ['USDT'],
    "PDEX": ['USDT'],
    "GALA": ['USDT', 'ETH'],
    "PYR": ['ETH', 'USDT'],
    "TRG": ['USDT'],
    "PNT": ['ETH', 'USDT'],
    "QUICK": ['USDT', 'ETH'],
    "MOOO": ['USDT'],
    "IAG": ['USDT'],
    "AAVE3L": ['USDT'],
    "MAN": ['USDT', 'ETH'],
    "INTR": ['USDT'],
    "ATOLO": ['USDT'],
    "SPI": ['USDT', 'ETH'],
    "KTON": ['USDT'],
    "QBT": ['ETH', 'USDT'],
    "MTL3L": ['USDT'],
    "POOLZ": ['ETH', 'USDT'],
    "QRDO": ['USDT', 'BTC', 'ETH'],
    "MASK": ['USDT', 'ETH'],
    "ALCX": ['USDT', 'ETH'],
    "OKB3L": ['USDT'],
    "ZTG": ['USDT'],
    "ADA3L": ['USDT'],
    "RGT": ['ETH', 'USDT'],
    "SHIB3S": ['USDT'],
    "MATIC3L": ['USDT'],
    "SLM": ['USDT'],
    "BSV5L": ['USDT'],
    "LYM": ['ETH', 'BTC', 'USDT'],
    "AXS": ['USDT', 'ETH'],
    "BRKL": ['USDT'],
    "STC": ['USDT'],
    "SDAO": ['BTC', 'USDT', 'ETH'],
    "LTC3L": ['USDT'],
    "IPUNKS": ['USDT'],
    "XNL": ['USDT'],
    "CVC3S": ['USDT'],
    "SCRT": ['USDT', 'ETH'],
    "ICP3L": ['USDT'],
    "DYDX3L": ['USDT'],
    "XLM3S": ['USDT'],
    "SN": ['USDT'],
    "REF": ['USDT'],
    "CRBN": ['USDT', 'ETH'],
    "ROUTE": ['USDT'],
    "MINA3L": ['USDT'],
    "AMPL": ['USDT'],
    "COREUM": ['USDT'],
    "ADAPAD": ['USDT'],
    "AFC": ['USDT'],
    "PORTX": ['USDT'],
    "KWS": ['USDT'],
    "INV": ['USDT', 'ETH'],
    "EGG": ['USDT', 'ETH'],
    "DOT": ['BTC', 'USDT'],
    "SHIB5S": ['USDT'],
    "FARM": ['ETH', 'USDT'],
    "BCDN": ['ETH', 'USDT'],
    "DOGE5S": ['USDT'],
    "MPL": ['USDT'],
    "BLZ": ['USDT', 'ETH'],
    "FLUX": ['USDT', 'ETH'],
    "GMM": ['USDT'],
    "DIA": ['USDT', 'ETH'],
    "YFI": ['ETH', 'USDT'],
    "GQ": ['USDT'],
    "MIS": ['USDT', 'ETH'],
    "BAC": ['USDT', 'ETH'],
    "PSB": ['USDT'],
    "LOOT": ['USDT'],
    "OUSD": ['USDT'],
    "MEETONE": ['ETH'],
    "CIR": ['USDT', 'ETH'],
    "NSDX": ['USDT'],
    "BLES": ['ETH', 'USDT'],
    "ECOX": ['USDT'],
    "EGS": ['USDT'],
    "ELEC": ['USDT', 'ETH'],
    "LITH": ['ETH', 'USDT'],
    "AR": ['USDT'],
    "10SET": ['USDT'],
    "ALICE": ['USDT', 'ETH'],
    "TRX3L": ['USDT'],
    "BMON": ['USDT', 'ETH'],
    "ZAM": ['ETH', 'USDT'],
    "LPOOL": ['USDT', 'ETH'],
    "BLOCK": ['USDT'],
    "MAPE": ['USDT'],
    "FTT3L": ['USDT'],
    "PPAD": ['USDT'],
    "ANC3S": ['USDT'],
    "GALA5L": ['USDT'],
    "VRT": ['USDT', 'ETH'],
    "TOMO": ['USDT', 'ETH'],
    "SFP": ['ETH', 'USDT'],
    "NEO3S": ['USDT'],
    "XMR3S": ['USDT'],
    "HOD": ['USDT'],
    "UDO": ['ETH', 'USDT'],
    "XET": ['USDT'],
    "ACE": ['USDT'],
    "DAI": ['USDT'],
    "OGV": ['USDT'],
    "COFI": ['USDT', 'ETH'],
    "CUMMIES": ['USDT'],
    "KLAY3S": ['USDT'],
    "XRUNE": ['USDT'],
    "TRIBE": ['USDT', 'ETH'],
    "DODO": ['ETH', 'USDT'],
    "CVC3L": ['USDT'],
    "TT": ['ETH', 'USDT'],
    "BVT": ['USDT'],
    "LBK": ['USDT'],
    "NKN": ['ETH', 'USDT'],
    "KON": ['USDT'],
    "SNOW": ['USDT', 'ETH'],
    "XEC": ['USDT'],
    "REVOLAND": ['USDT'],
    "CHAIN": ['ETH', 'USDT'],
    "VLX": ['USDT'],
    "ZIL3S": ['USDT'],
    "CFX": ['USDT', 'ETH'],
    "GAN": ['USDT'],
    "GS": ['ETH', 'USDT'],
    "DSD": ['USDT', 'ETH'],
    "METO": ['USDT'],
    "SLP3L": ['USDT'],
    "SKRT": ['USDT'],
    "BENQI": ['USDT', 'ETH'],
    "BTCST": ['USDT', 'ETH'],
    "ZEUM": ['USDT'],
    "USDN": ['USDT'],
    "AAG": ['USDT'],
    "MARSH": ['USDT', 'ETH'],
    "KLAP": ['USDT'],
    "DASH3S": ['USDT'],
    "SAFEMARS": ['USDT'],
    "SPHRI": ['USDT'],
    "KIN": ['USDT'],
    "DASH": ['USDT', 'BTC'],
    "ATK": ['USDT', 'ETH'],
    "PSL": ['USDT'],
    "GLMR": ['USDT', 'ETH'],
    "DOSE": ['USDT', 'ETH'],
    "BNX": ['USDT'],
    "MCRT": ['USDT'],
    "HT3L": ['USDT'],
    "MATH": ['USDT', 'ETH'],
    "GNX": ['USDT', 'ETH'],
    "MILO": ['USDT'],
    "MTN": ['USDT', 'ETH'],
    "MNZ": ['USDT'],
    "AUDIO": ['USDT', 'ETH'],
    "CRO": ['USDT'],
    "FOF": ['USDT'],
    "ZCX": ['USDT'],
    "EOSBULL": ['USDT'],
    "SKL3L": ['USDT'],
    "GST3S": ['USDT'],
    "VINU": ['USDT'],
    "ITSB": ['USDT'],
    "BOSON": ['USDT', 'ETH'],
    "CVTX": ['USDT'],
    "RSS3": ['USDT'],
    "PRIDE": ['USDT'],
    "HCT": ['ETH', 'USDT'],
    "EGLD3L": ['USDT'],
    "DYDX3S": ['USDT'],
    "DANA": ['USDT'],
    "MNW": ['ETH', 'USDT'],
    "GARD": ['USDT', 'ETH'],
    "MTD": ['USDT'],
    "ORBR": ['USDT'],
    "DLTA": ['USDT'],
    "XCV": ['ETH', 'USDT'],
    "SFIL": ['USDT'],
    "FALCONS": ['USDT'],
    "APE3S": ['USDT'],
    "XEN": ['USDT'],
    "ALGO3S": ['USDT'],
    "PSTAKE": ['USDT'],
    "MED": ['ETH', 'USDT'],
    "BIT": ['USDT'],
    "EON": ['ETH'],
    "MANA3S": ['USDT'],
    "SNET": ['USDT', 'ETH'],
    "LIKE": ['ETH', 'USDT'],
    "SAND3L": ['USDT'],
    "ARPA3L": ['USDT'],
    "SHARE": ['USDT', 'ETH'],
    "TEDDY": ['USDT'],
    "BAS": ['USDT', 'ETH'],
    "ZEC": ['BTC', 'USDT'],
    "NIF": ['USDT'],
    "INDI": ['USDT', 'ETH'],
    "KINGSHIB": ['USDT'],
    "ETHA": ['USDT', 'ETH'],
    "KBOX": ['USDT'],
    "HID": ['USDT'],
    "ALPINE": ['USDT'],
    "SHILL": ['USDT'],
    "LRC3L": ['USDT'],
    "PIZA": ['USDT'],
    "DOT5S": ['USDT'],
    "FORM": ['USDT', 'ETH'],
    "REALM": ['USDT'],
    "LON3L": ['USDT'],
    "AVA": ['USDT'],
    "ANC": ['ETH', 'USDT'],
    "COTI3L": ['USDT'],
    "XPLA": ['USDT'],
    "PUNDIX": ['ETH', 'USDT'],
    "XLM3L": ['USDT'],
    "THN": ['ETH', 'USDT'],
    "ACA": ['USDT'],
    "RLC": ['USDT', 'ETH'],
    "GLMR3S": ['USDT'],
    "HUR": ['ETH'],
    "OVR": ['USDT'],
    "DHV": ['USDT', 'ETH'],
    "BCH3S": ['USDT'],
    "AVAX3S": ['USDT'],
    "MASK3S": ['USDT'],
    "FIL3L": ['USDT'],
    "AXL": ['USDT'],
    "URUS": ['ETH', 'USDT'],
    "BP": ['USDT'],
    "DILI": ['USDT'],
    "PORT": ['USDT'],
    "REVU": ['USDT'],
    "PKF": ['USDT', 'ETH'],
    "LTC5L": ['USDT'],
    "SRT": ['USDT'],
    "GOVI": ['USDT'],
    "CRT": ['USDT'],
    "RUNE3L": ['USDT'],
    "PAF": ['USDT'],
    "QNT": ['ETH', 'USDT'],
    "SOLO": ['BTC', 'USDT'],
    "DOCK": ['USDT', 'ETH'],
    "RUNE3S": ['USDT'],
    "GMX": ['USDT'],
    "DAFI": ['USDT', 'ETH'],
    "MEPAD": ['USDT'],
    "LTC3S": ['USDT'],
    "NYM": ['USDT'],
    "THALES": ['USDT'],
    "FOR": ['USDT', 'ETH'],
    "DES": ['USDT'],
    "HOOK": ['USDT'],
    "ZBC": ['USDT'],
    "CTC": ['USDT'],
    "HIBIKI": ['USDT'],
    "PRQ": ['USDT'],
    "XRP5L": ['USDT'],
    "POT": ['USDT'],
    "KLAY": ['USDT'],
    "ETH3L": ['USDT'],
    "CAKE3L": ['USDT'],
    "GAL": ['USDT'],
    "CAKE": ['ETH', 'USDT'],
    "PUSH": ['ETH', 'USDT'],
    "ONIT": ['USDT'],
    "BLT": ['USDT'],
    "TRIBE3S": ['USDT'],
    "USDD": ['USDT'],
    "XRPBEAR": ['USDT'],
    "FIS": ['USDT', 'ETH'],
    "CERE": ['USDT', 'ETH'],
    "TAI": ['USDT'],
    "OKB": ['USDT'],
    "ZEC3L": ['USDT'],
    "TAP": ['USDT'],
    "MSWAP": ['USDT'],
    "PEOPLE": ['USDT'],
    "SNT": ['BTC', 'ETH', 'USDT'],
    "FTRB": ['USDT'],
    "XRPBULL": ['USDT'],
    "VADER": ['ETH', 'USDT'],
    "SNK": ['USDT'],
    "BONK": ['USDT'],
    "TIDAL": ['USDT', 'ETH'],
    "NOA": ['USDT'],
    "APRT": ['USDT'],
    "NUM": ['USDT'],
    "RIM": ['USDT'],
    "ETH5S": ['USDT'],
    "GALA3L": ['USDT'],
    "DVI": ['USDT'],
    "DIGG": ['ETH', 'USDT'],
    "SWEAT": ['USDT'],
    "ONE3S": ['USDT'],
    "ARSW": ['USDT'],
    "POSI": ['USDT'],
    "SUN": ['USDT'],
    "MOJO": ['USDT'],
    "IBAYC": ['USDT'],
    "DASH3L": ['USDT'],
    "BSW3S": ['USDT'],
    "IMX3S": ['USDT'],
    "BZZ3L": ['USDT'],
    "SIS": ['USDT'],
    "LTO": ['USDT', 'ETH'],
    "DOT3L": ['USDT'],
    "POP": ['USDT'],
    "BABY": ['USDT'],
    "MTL": ['USDT', 'ETH'],
    "1INCH3S": ['USDT'],
    "ALY": ['USDT'],
    "VET3L": ['USDT'],
    "BBF": ['USDT'],
    "ACH3L": ['USDT'],
    "BCH5S": ['USDT'],
    "AGS": ['USDT'],
    "TOMI": ['USDT'],
    "DOT5L": ['USDT'],
    "JASMY3L": ['USDT'],
    "CHAMP": ['USDT'],
    "SWP": ['USDT'],
    "AR3S": ['USDT'],
    "DOGA": ['USDT'],
    "100X": ['USDT'],
    "SOL3S": ['USDT'],
    "ELA": ['USDT'],
    "DFI": ['USDT'],
    "REDTOKEN": ['USDT'],
    "BLANK": ['ETH', 'USDT'],
    "ISKY": ['USDT'],
    "ALGO": ['USDT'],
    "AIRTNT": ['USDT'],
    "AOG": ['USDT'],
    "JOY": ['USDT'],
    "SHIB": ['USDT'],
    "CPOOL": ['USDT'],
    "BADGER": ['USDT', 'ETH'],
    "CHER": ['USDT'],
    "ATOM3S": ['USDT'],
    "SHIB3L": ['USDT'],
    "XAUT": ['USDT'],
    "DIVER": ['USDT'],
    "SXP3S": ['USDT'],
    "GHNY": ['USDT'],
    "OP3L": ['USDT'],
    "KT": ['USDT'],
    "KUB": ['USDT'],
    "YCT": ['USDT'],
    "MMPRO": ['USDT'],
    "PARA": ['USDT'],
    "TABOO": ['USDT'],
    "1EARTH": ['USDT'],
    "APX": ['USDT'],
    "SHIB5L": ['USDT'],
    "VENT": ['USDT'],
    "CFX3S": ['USDT'],
    "TRIBE3L": ['USDT'],
    "ADS": ['USDT'],
    "RAY": ['USDT', 'ETH'],
    "BAL3L": ['USDT'],
    "UFI": ['USDT'],
    "SANTOS": ['USDT'],
    "DEFILAND": ['ETH', 'USDT'],
    "ALPHA3L": ['USDT'],
    "F2C": ['USDT'],
    "MET": ['USDT'],
    "IOST3L": ['USDT'],
    "ALPHA3S": ['USDT'],
    "STZ": ['USDT'],
    "DLC": ['USDT'],
    "OIN": ['USDT'],
    "ENJ3L": ['USDT'],
    "MV": ['USDT'],
    "PLACE": ['USDT'],
    "BSV3S": ['USDT'],
    "WAVES3S": ['USDT'],
    "CARE": ['USDT'],
    "XELS": ['USDT'],
    "BCH3L": ['USDT'],
    "KUBE": ['USDT'],
    "ANML": ['USDT'],
    "ONT3L": ['USDT'],
    "THE": ['USDT'],
    "DOGE5L": ['USDT'],
    "BNC": ['USDT'],
    "VDR": ['USDT'],
    "REAP": ['USDT'],
    "WOO3S": ['USDT'],
    "BFT1": ['USDT'],
    "OMG3S": ['USDT'],
    "ZEN3S": ['USDT'],
    "LUS": ['USDT'],
    "VRJAM": ['USDT'],
    "GLMR3L": ['USDT'],
    "PEARL": ['USDT'],
    "ETHBEAR": ['USDT'],
    "TSUKA": ['USDT'],
    "NWC": ['USDT', 'BTC'],
    "FIN": ['USDT'],
    "HYDRA": ['USDT'],
    "ACM": ['USDT'],
    "GGG": ['USDT'],
    "MCASH": ['USDT'],
    "LOA": ['USDT'],
    "SUSHI3S": ['USDT'],
    "AQDC": ['USDT'],
    "YFII3S": ['USDT'],
    "USTC": ['USDT'],
    "OSMO": ['USDT'],
    "BNB3S": ['USDT'],
    "COVAL": ['USDT'],
    "DSLA": ['ETH', 'USDT'],
    "FITFI3S": ['USDT'],
    "MTL3S": ['USDT'],
    "XRP5S": ['USDT'],
    "GST3L": ['USDT'],
    "DOS": ['USDT'],
    "BTCBEAR": ['USDT'],
    "MHUNT": ['USDT'],
    "RIN": ['USDT'],
    "SD": ['USDT'],
    "TIP": ['USDT'],
    "FIC": ['USDT'],
    "VET3S": ['USDT'],
    "PCX": ['USDT'],
    "KAR": ['USDT'],
    "WAG": ['USDT'],
    "C983L": ['USDT'],
    "KALM": ['USDT'],
    "WLKN": ['USDT'],
    "KZEN": ['USDT'],
    "BAT3S": ['USDT'],
    "HIBS": ['USDT'],
    "DEP": ['USDT'],
    "TRACE": ['USDT'],
    "THG": ['USDT'],
    "CPAN": ['USDT'],
    "REN": ['USDT', 'ETH'],
    "EOS5L": ['USDT'],
    "SHX": ['USDT'],
    "BATH": ['USDT', 'ETH'],
    "ATOM": ['BTC', 'USDT'],
    "GM": ['USDT'],
    "SLG": ['USDT'],
    "OLE": ['USDT'],
    "MCG": ['USDT'],
    "SPUME": ['USDT'],
    "YFI3S": ['USDT'],
    "UNCX": ['USDT'],
    "PLSPAD": ['USDT'],
    "SYLO": ['USDT'],
    "ROSE3S": ['USDT'],
    "XEC3S": ['USDT'],
    "NFTL": ['USDT'],
    "BERRY": ['USDT'],
    "CRV3S": ['USDT'],
    "HTR": ['USDT'],
    "GAL3L": ['USDT'],
    "MBX": ['USDT'],
    "MDA": ['ETH', 'USDT'],
    "PLCU": ['USDT'],
    "RENA": ['USDT'],
    "OLV": ['USDT'],
    "AVT": ['USDT'],
    "ALPACA": ['USDT', 'ETH'],
    "XMR3L": ['USDT'],
    "RON": ['USDT'],
    "SAVG": ['USDT'],
    "PRIMAL": ['USDT'],
    "VET": ['ETH', 'USDT'],
    "GMT3L": ['USDT'],
    "DOE": ['USDT'],
    "DFYN": ['USDT'],
    "BLIN": ['USDT'],
    "APE": ['USDT'],
    "KSM3S": ['USDT'],
    "FRIN": ['USDT'],
    "JUV": ['USDT'],
    "DOT3S": ['USDT'],
    "DELFI": ['USDT'],
    "BTM3S": ['USDT'],
    "ITEM": ['USDT'],
    "WSG": ['USDT'],
    "WEAR": ['USDT'],
    "CHZ3L": ['USDT'],
    "AXS5L": ['USDT'],
    "IRIS": ['USDT'],
    "KABY": ['USDT'],
    "NFT": ['USDT'],
    "NBAI": ['ETH'],
    "KICKS": ['USDT'],
    "DOME": ['USDT'],
    "POLIS": ['USDT'],
    "ROCO": ['USDT'],
    "SFG": ['USDT'],
    "MINT": ['USDT'],
    "AQT": ['USDT'],
    "STPT": ['USDT'],
    "THETA3S": ['USDT']
}


GATE_IO_SUPPORTING_SYMBOLS = list(GATE_IO_SYMBOL_TO_ANCHORS.keys())
